# backend/seed/diseases.py
# 40 disease records across 5 crops (8 per crop)

diseases = [
    # ── Tomato Diseases ─────────────────────
    {"id": "d1", "plant_id": "p1", "name": "Early Blight", "scientific_name": "Alternaria solani",
     "description": "Fungal disease causing concentric ring-shaped lesions on older leaves.",
     "symptoms": ["dark concentric rings on leaves", "yellowing around spots", "leaf drop from bottom up", "stem lesions"],
     "conditions": ["high humidity", "warm temperature 24-30C", "overhead irrigation"],
     "severity": "high"},
    {"id": "d2", "plant_id": "p1", "name": "Late Blight", "scientific_name": "Phytophthora infestans",
     "description": "Devastating oomycete disease that can destroy entire crop within days.",
     "symptoms": ["water-soaked grey-green spots", "white fuzzy growth on leaf underside", "fruit turning brown", "rapid wilting"],
     "conditions": ["cool wet weather", "temperature 15-22C", "high humidity above 90%"],
     "severity": "critical"},
    {"id": "d3", "plant_id": "p1", "name": "Bacterial Wilt", "scientific_name": "Ralstonia solanacearum",
     "description": "Soil-borne bacterial disease causing sudden wilting without yellowing.",
     "symptoms": ["sudden wilting of whole plant", "no yellowing before wilt", "brown vascular tissue", "bacterial ooze from cut stem"],
     "conditions": ["warm soil above 25C", "waterlogged conditions", "acidic soil"],
     "severity": "critical"},
    {"id": "d4", "plant_id": "p1", "name": "Fusarium Wilt", "scientific_name": "Fusarium oxysporum",
     "description": "Soil-borne fungus blocking water transport in the plant.",
     "symptoms": ["yellowing of lower leaves on one side", "progressive wilting", "brown discoloration in stem", "stunted growth"],
     "conditions": ["warm soil 27-30C", "acidic soil", "poor drainage"],
     "severity": "high"},
    {"id": "d5", "plant_id": "p1", "name": "Leaf Curl Virus", "scientific_name": "Tomato leaf curl virus (ToLCV)",
     "description": "Viral disease transmitted by whiteflies causing severe leaf deformation.",
     "symptoms": ["upward curling of leaves", "thickened leathery leaves", "stunted growth", "yellow margins"],
     "conditions": ["whitefly infestation", "dry hot weather", "monoculture"],
     "severity": "high"},
    {"id": "d6", "plant_id": "p1", "name": "Blossom End Rot", "scientific_name": None,
     "description": "Physiological disorder caused by calcium deficiency or irregular watering.",
     "symptoms": ["dark sunken patch at fruit bottom", "brown leathery tissue", "affects green and ripe fruits"],
     "conditions": ["irregular watering", "calcium deficiency", "high nitrogen"],
     "severity": "medium"},
    {"id": "d7", "plant_id": "p1", "name": "Powdery Mildew", "scientific_name": "Leveillula taurica",
     "description": "Fungal disease producing white powdery growth on leaf surfaces.",
     "symptoms": ["white powdery patches on leaves", "yellow spots on upper leaf surface", "leaf drying", "reduced photosynthesis"],
     "conditions": ["dry weather", "moderate temperature 20-25C", "poor air circulation"],
     "severity": "medium"},
    {"id": "d8", "plant_id": "p1", "name": "Septoria Leaf Spot", "scientific_name": "Septoria lycopersici",
     "description": "Fungal disease causing numerous small spots on lower leaves.",
     "symptoms": ["small circular spots with dark border", "grey centers with tiny dots", "lower leaf yellowing", "premature defoliation"],
     "conditions": ["wet weather", "splashing rain", "warm temperature"],
     "severity": "medium"},

    # ── Chili Diseases ──────────────────────
    {"id": "d9", "plant_id": "p2", "name": "Anthracnose", "scientific_name": "Colletotrichum capsici",
     "description": "Major post-harvest disease causing sunken lesions on fruits.",
     "symptoms": ["sunken circular spots on fruits", "dark brown to black lesions", "concentric rings on pods", "fruit rotting"],
     "conditions": ["high humidity above 80%", "warm temperature 25-30C", "rain splashing"],
     "severity": "high"},
    {"id": "d10", "plant_id": "p2", "name": "Chili Leaf Curl", "scientific_name": "Chili leaf curl virus",
     "description": "Viral disease causing severe leaf distortion transmitted by whiteflies.",
     "symptoms": ["upward leaf curling", "puckering of leaves", "stunted plant growth", "reduced fruiting"],
     "conditions": ["whitefly vector", "hot dry conditions", "continuous cropping"],
     "severity": "high"},
    {"id": "d11", "plant_id": "p2", "name": "Damping Off", "scientific_name": "Pythium spp.",
     "description": "Soil-borne disease affecting seedlings at nursery stage.",
     "symptoms": ["seedling collapse at soil level", "water-soaked stem base", "pre-emergence seed rot", "thin weak stems"],
     "conditions": ["overwatering", "poor drainage", "dense sowing"],
     "severity": "high"},
    {"id": "d12", "plant_id": "p2", "name": "Cercospora Leaf Spot", "scientific_name": "Cercospora capsici",
     "description": "Fungal disease causing circular spots on chili leaves.",
     "symptoms": ["circular brown spots", "whitish grey center", "leaf yellowing", "premature leaf drop"],
     "conditions": ["humid conditions", "poor ventilation", "continuous cropping"],
     "severity": "medium"},
    {"id": "d13", "plant_id": "p2", "name": "Bacterial Leaf Spot", "scientific_name": "Xanthomonas campestris",
     "description": "Bacterial disease causing water-soaked lesions on leaves and fruits.",
     "symptoms": ["small water-soaked spots", "spots turn brown and necrotic", "raised bumps on fruits", "leaf defoliation"],
     "conditions": ["warm wet conditions", "overhead irrigation", "wind-driven rain"],
     "severity": "medium"},
    {"id": "d14", "plant_id": "p2", "name": "Powdery Mildew", "scientific_name": "Leveillula taurica",
     "description": "White powdery fungal growth on leaves reducing photosynthesis.",
     "symptoms": ["white powdery coating", "yellowing patches", "leaf curling downward", "premature leaf fall"],
     "conditions": ["moderate humidity", "warm days cool nights", "poor airflow"],
     "severity": "medium"},
    {"id": "d15", "plant_id": "p2", "name": "Fusarium Wilt", "scientific_name": "Fusarium oxysporum f.sp. capsici",
     "description": "Soil-borne wilt disease causing vascular browning.",
     "symptoms": ["yellowing lower leaves", "progressive wilting", "brown vascular bundles", "plant death"],
     "conditions": ["warm soil", "acidic pH", "previous Solanaceae crops"],
     "severity": "high"},
    {"id": "d16", "plant_id": "p2", "name": "Fruit Rot", "scientific_name": "Phytophthora capsici",
     "description": "Water mold causing rapid fruit rotting especially after rain.",
     "symptoms": ["water-soaked fruit lesions", "white cottony growth", "rapid fruit decay", "dark brown patches"],
     "conditions": ["standing water", "heavy rainfall", "poor drainage"],
     "severity": "high"},

    # ── Rice Diseases ───────────────────────
    {"id": "d17", "plant_id": "p3", "name": "Blast Disease", "scientific_name": "Magnaporthe oryzae",
     "description": "Most devastating rice disease affecting leaves, nodes, and panicles.",
     "symptoms": ["diamond-shaped grey spots", "white to grey center", "neck blast at panicle base", "grain discoloration"],
     "conditions": ["high nitrogen", "cloudy weather", "temperature 25-28C"],
     "severity": "critical"},
    {"id": "d18", "plant_id": "p3", "name": "Bacterial Leaf Blight", "scientific_name": "Xanthomonas oryzae",
     "description": "Major bacterial disease causing leaf drying from tips.",
     "symptoms": ["yellow to white streaks from leaf tip", "wavy leaf margins", "entire leaf drying", "milky bacterial ooze"],
     "conditions": ["warm humid weather", "flooding", "strong winds with rain"],
     "severity": "high"},
    {"id": "d19", "plant_id": "p3", "name": "Sheath Blight", "scientific_name": "Rhizoctonia solani",
     "description": "Fungal disease causing irregular lesions on leaf sheaths.",
     "symptoms": ["oval greenish-grey lesions on sheath", "lesions merge upward", "lodging", "white powdery surface"],
     "conditions": ["dense planting", "high nitrogen", "warm humid 28-32C"],
     "severity": "high"},
    {"id": "d20", "plant_id": "p3", "name": "Brown Spot", "scientific_name": "Bipolaris oryzae",
     "description": "Fungal disease associated with nutrient deficiency.",
     "symptoms": ["oval brown spots", "grey center", "spots on glumes", "poor grain filling"],
     "conditions": ["nutrient-deficient soil", "drought stress", "poor management"],
     "severity": "medium"},
    {"id": "d21", "plant_id": "p3", "name": "Tungro Virus", "scientific_name": "Rice tungro virus",
     "description": "Viral complex transmitted by green leafhoppers.",
     "symptoms": ["yellow-orange leaf discoloration", "stunted plants", "reduced tillering", "delayed flowering"],
     "conditions": ["leafhopper presence", "early season infection", "susceptible varieties"],
     "severity": "high"},
    {"id": "d22", "plant_id": "p3", "name": "False Smut", "scientific_name": "Ustilaginoidea virens",
     "description": "Fungal disease converting rice grains into large spore balls.",
     "symptoms": ["orange to green spore balls on panicle", "individual grains replaced", "velvety appearance", "reduced yield"],
     "conditions": ["high humidity at flowering", "overcast weather", "high nitrogen"],
     "severity": "medium"},
    {"id": "d23", "plant_id": "p3", "name": "Stem Rot", "scientific_name": "Sclerotium oryzae",
     "description": "Fungal disease causing stem weakening and lodging.",
     "symptoms": ["black lesions at water line", "hollow stems", "premature ripening", "lodging at maturity"],
     "conditions": ["continuous flooding", "high nitrogen", "stubble not decomposed"],
     "severity": "medium"},
    {"id": "d24", "plant_id": "p3", "name": "Grain Discoloration", "scientific_name": "Multiple fungi",
     "description": "Complex of fungi discolouring rice grains, reducing market value.",
     "symptoms": ["dark spots on grains", "chalky grains", "discoloured husks", "reduced milling quality"],
     "conditions": ["wet weather at maturity", "delayed harvest", "insect damage"],
     "severity": "medium"},

    # ── Brinjal Diseases ────────────────────
    {"id": "d25", "plant_id": "p4", "name": "Bacterial Wilt", "scientific_name": "Ralstonia solanacearum",
     "description": "Soil-borne bacterial wilt — most serious brinjal disease in tropics.",
     "symptoms": ["sudden wilting", "no leaf yellowing", "brown vascular tissue", "bacterial streaming in water test"],
     "conditions": ["warm wet soil", "acidic conditions", "previous Solanaceae crop"],
     "severity": "critical"},
    {"id": "d26", "plant_id": "p4", "name": "Phomopsis Blight", "scientific_name": "Phomopsis vexans",
     "description": "Fungal disease causing leaf spots and fruit rot.",
     "symptoms": ["circular leaf spots with concentric rings", "fruit rot with soft brown areas", "stem cankers", "damping off in nursery"],
     "conditions": ["high humidity", "warm temperature", "splashing rain"],
     "severity": "high"},
    {"id": "d27", "plant_id": "p4", "name": "Little Leaf", "scientific_name": "Phytoplasma",
     "description": "Phytoplasma disease causing extreme leaf reduction.",
     "symptoms": ["very small leaves", "excessive branching", "bushy stunted plant", "green flowers"],
     "conditions": ["leafhopper vector", "warm season", "weed hosts nearby"],
     "severity": "high"},
    {"id": "d28", "plant_id": "p4", "name": "Cercospora Leaf Spot", "scientific_name": "Cercospora melongenae",
     "description": "Fungal leaf spot disease of brinjal.",
     "symptoms": ["angular chlorotic spots", "spots turn brown", "shot-hole appearance", "defoliation"],
     "conditions": ["humid weather", "overcrowding", "poor drainage"],
     "severity": "medium"},
    {"id": "d29", "plant_id": "p4", "name": "Verticillium Wilt", "scientific_name": "Verticillium dahliae",
     "description": "Soil-borne fungus causing progressive wilting.",
     "symptoms": ["V-shaped yellowing on leaves", "wilting during hot days", "recovery at night initially", "brown vascular tissue"],
     "conditions": ["cool soil 20-24C", "previously infected soil", "wet conditions"],
     "severity": "high"},
    {"id": "d30", "plant_id": "p4", "name": "Damping Off", "scientific_name": "Pythium spp. / Rhizoctonia spp.",
     "description": "Seedling disease in nursery causing collar rot.",
     "symptoms": ["seedling collapse", "water-soaked stem at soil line", "brown rotting base", "pre-emergence death"],
     "conditions": ["overwatering", "dense sowing", "poor ventilation"],
     "severity": "high"},
    {"id": "d31", "plant_id": "p4", "name": "Powdery Mildew", "scientific_name": "Erysiphe cichoracearum",
     "description": "White powdery fungal growth on brinjal leaves.",
     "symptoms": ["white powdery patches", "yellowing leaves", "leaf curling", "premature defoliation"],
     "conditions": ["dry warm weather", "poor air circulation", "shaded areas"],
     "severity": "medium"},
    {"id": "d32", "plant_id": "p4", "name": "Mosaic Virus", "scientific_name": "Eggplant mosaic virus",
     "description": "Viral disease causing mottled leaf patterns.",
     "symptoms": ["light and dark green mottling", "leaf distortion", "stunted growth", "reduced fruit size"],
     "conditions": ["aphid vectors", "weed reservoirs", "mechanical transmission"],
     "severity": "medium"},

    # ── Beans Diseases ──────────────────────
    {"id": "d33", "plant_id": "p5", "name": "Anthracnose", "scientific_name": "Colletotrichum lindemuthianum",
     "description": "Seed-borne fungal disease causing dark sunken lesions on pods.",
     "symptoms": ["dark sunken spots on pods", "reddish-brown veins on leaves", "pod twisting", "seed discoloration"],
     "conditions": ["cool humid weather", "infected seed", "overhead irrigation"],
     "severity": "high"},
    {"id": "d34", "plant_id": "p5", "name": "Rust", "scientific_name": "Uromyces appendiculatus",
     "description": "Fungal disease producing rusty brown pustules on leaves.",
     "symptoms": ["small reddish-brown pustules", "powdery spores when rubbed", "yellow halo around pustules", "severe defoliation"],
     "conditions": ["warm humid 17-27C", "morning dew", "dense canopy"],
     "severity": "high"},
    {"id": "d35", "plant_id": "p5", "name": "Angular Leaf Spot", "scientific_name": "Phaeoisariopsis griseola",
     "description": "Fungal disease causing angular lesions limited by leaf veins.",
     "symptoms": ["angular grey-brown spots", "lesions bounded by veins", "spots on pods", "premature defoliation"],
     "conditions": ["warm humid weather", "poor air flow", "infected seed"],
     "severity": "medium"},
    {"id": "d36", "plant_id": "p5", "name": "Common Bacterial Blight", "scientific_name": "Xanthomonas axonopodis",
     "description": "Bacterial disease causing water-soaked lesions on leaves.",
     "symptoms": ["water-soaked spots on leaves", "yellow halo around lesions", "brown necrotic patches", "pod lesions"],
     "conditions": ["warm wet weather", "splashing rain", "infected seed"],
     "severity": "medium"},
    {"id": "d37", "plant_id": "p5", "name": "Root Rot", "scientific_name": "Rhizoctonia solani",
     "description": "Soil-borne disease causing root and lower stem rotting.",
     "symptoms": ["reddish-brown lesions on stem base", "wilting plants", "poor root system", "plant death"],
     "conditions": ["waterlogged soil", "compacted soil", "cool wet conditions"],
     "severity": "high"},
    {"id": "d38", "plant_id": "p5", "name": "Bean Mosaic Virus", "scientific_name": "Bean common mosaic virus",
     "description": "Seed-borne viral disease causing leaf mottling.",
     "symptoms": ["green mosaic pattern", "leaf curling downward", "puckered leaves", "stunted pods"],
     "conditions": ["aphid transmission", "infected seed", "warm season"],
     "severity": "medium"},
    {"id": "d39", "plant_id": "p5", "name": "Powdery Mildew", "scientific_name": "Erysiphe polygoni",
     "description": "White powdery fungal growth on bean leaves and pods.",
     "symptoms": ["white powdery growth", "yellowing leaves", "premature leaf drop", "pod surface affected"],
     "conditions": ["dry warm days", "cool nights", "poor ventilation"],
     "severity": "medium"},
    {"id": "d40", "plant_id": "p5", "name": "Halo Blight", "scientific_name": "Pseudomonas syringae pv. phaseolicola",
     "description": "Bacterial disease producing spots with prominent green-yellow halo.",
     "symptoms": ["small water-soaked spots", "large greenish-yellow halo", "systemic yellowing", "cream-coloured bacterial ooze"],
     "conditions": ["cool wet weather", "splashing rain", "seed-borne"],
     "severity": "high"},

    # ── Onion Diseases (p6) ──────────────────
    {"id": "d41", "plant_id": "p6", "name": "Purple Blotch", "scientific_name": "Alternaria porri",
     "description": "Fungal disease causing purple lesions on leaves and bulb necks.",
     "symptoms": ["purple oval lesions on leaves", "yellow fading leaf tips", "dark concentric circles", "rotting bulb neck"],
     "conditions": ["high humidity above 80%", "warm temperature 25-30C", "dew or rain"],
     "severity": "high"},
    {"id": "d42", "plant_id": "p6", "name": "Downy Mildew", "scientific_name": "Peronospora destructor",
     "description": "Systemic fungal infection causing fuzzy violet-grey growth on leaves.",
     "symptoms": ["violet-grey powdery growth", "pale green leaves", "leaves collapse and die", "stunted bulbs"],
     "conditions": ["cool wet weather", "temperature 10-22C", "prolonged leaf wetness"],
     "severity": "critical"},
    {"id": "d43", "plant_id": "p6", "name": "Onion Smudge", "scientific_name": "Colletotrichum circinans",
     "description": "Fungal disease causing dark smudges on outer bulb scales.",
     "symptoms": ["dark green or black smudges", "concentric rings of black dots", "shrivelled outer scales", "premature leaf yellowing"],
     "conditions": ["warm wet soil", "temperature 20-28C", "poor drainage"],
     "severity": "medium"},
    {"id": "d44", "plant_id": "p6", "name": "Black Mold", "scientific_name": "Aspergillus niger",
     "description": "Fungal disease causing black powdery spore masses under outer bulb scales.",
     "symptoms": ["black powdery spores under bulb scales", "softening of bulb tissue", "shrivelling", "musty smell"],
     "conditions": ["hot dry conditions during maturity", "temperature above 30C", "bruising during harvest"],
     "severity": "medium"},
    {"id": "d45", "plant_id": "p6", "name": "Fusarium Bulb Rot", "scientific_name": "Fusarium oxysporum",
     "description": "Soil-borne fungus causing root rot and progressive bulb decay.",
     "symptoms": ["leaf yellowing and wilting", "root rot", "white/pink mold at bulb base", "soft watery bulbs"],
     "conditions": ["warm soil above 28C", "poor drainage", "mechanical injury to roots"],
     "severity": "high"},

    # ── Potato Diseases (p7) ─────────────────
    {"id": "d46", "plant_id": "p7", "name": "Late Blight of Potato", "scientific_name": "Phytophthora infestans",
     "description": "Devastating oomycete causing rapid leaf blight and tuber rot.",
     "symptoms": ["dark green water-soaked spots", "white fuzzy growth under leaves", "tuber skin turning brown/purple", "brown dry rot in tuber flesh"],
     "conditions": ["cool humid weather", "temperature 15-20C", "frequent rainfall"],
     "severity": "critical"},
    {"id": "d47", "plant_id": "p7", "name": "Black Scurf", "scientific_name": "Rhizoctonia solani",
     "description": "Fungal disease leaving black sclerotia on tuber surfaces.",
     "symptoms": ["black dirt-like patches on tuber skin", "cankers on sprouts", "stunted plants", "aerial tubers"],
     "conditions": ["cool wet soil", "delayed harvest", "acidic soil"],
     "severity": "high"},
    {"id": "d48", "plant_id": "p7", "name": "Common Scab", "scientific_name": "Streptomyces scabies",
     "description": "Bacterial disease causing corky lesions on tuber skins.",
     "symptoms": ["corky raised lesions on tuber skin", "rough pitted skin patches", "cratering on tubers", "unaffected foliage"],
     "conditions": ["dry soil during tuber initiation", "alkaline soil pH above 6.5", "fresh manure application"],
     "severity": "medium"},
    {"id": "d49", "plant_id": "p7", "name": "Bacterial Soft Rot", "scientific_name": "Pectobacterium carotovorum",
     "description": "Bacterial decay turning tuber tissue into soft, foul-smelling mush.",
     "symptoms": ["water-soaked spots on stems", "mushy tuber tissue", "foul odor from rotten tubers", "sudden plant collapse"],
     "conditions": ["wet soil", "harvest injury", "poor storage ventilation"],
     "severity": "critical"},
    {"id": "d50", "plant_id": "p7", "name": "Potato Leaf Roll Virus", "scientific_name": "Potato leafroll virus (PLRV)",
     "description": "Aphid-transmitted virus causing leaf rolling and phloem necrosis.",
     "symptoms": ["upward rolling of lower leaves", "leathery leaf texture", "pale yellow foliage", "net necrosis inside tubers"],
     "conditions": ["high aphid population", "poor seed quality", "continuous potato planting"],
     "severity": "high"},

    # ── Cassava Diseases (p8) ────────────────
    {"id": "d51", "plant_id": "p8", "name": "Cassava Mosaic Disease", "scientific_name": "Cassava mosaic geminivirus",
     "description": "Viral disease transmitted by whiteflies causing severe leaf chlorosis.",
     "symptoms": ["mottling and chlorosis of leaves", "deformed twisted leaflets", "stunted plant growth", "reduced tuber size"],
     "conditions": ["whitefly infestation", "infected cuttings used for planting", "susceptible cultivars"],
     "severity": "critical"},
    {"id": "d52", "plant_id": "p8", "name": "Cassava Brown Streak Disease", "scientific_name": "Cassava brown streak virus",
     "description": "Viral disease causing stem necrosis and brown corky rot inside tubers.",
     "symptoms": ["yellow chlorosis along leaf veins", "brown necrotic streaks on stems", "dry brown necrotic rot in tubers", "cracking of tuber skins"],
     "conditions": ["whitefly transmission", "diseased planting material", "low altitude wet zones"],
     "severity": "critical"},
    {"id": "d53", "plant_id": "p8", "name": "Cassava Bacterial Blight", "scientific_name": "Xanthomonas axonopodis pv. manihotis",
     "description": "Bacterial disease causing leaf wilting, blight, and gum exudation.",
     "symptoms": ["angular water-soaked leaf spots", "wilting of young leaves", "dieback of stems", "yellowish gum on stems"],
     "conditions": ["warm wet season", "splashing rain", "contaminated tools"],
     "severity": "high"},
    {"id": "d54", "plant_id": "p8", "name": "Anthracnose of Cassava", "scientific_name": "Colletotrichum gloeosporioides",
     "description": "Fungal infection causing leaf spots and cankers on young stems.",
     "symptoms": ["brown spots on leaves", "leaf drop", "sunken cankers on young stems", "cuttings rotting"],
     "conditions": ["high humidity", "rainy season", "unweeded dense fields"],
     "severity": "medium"},
    {"id": "d55", "plant_id": "p8", "name": "Root Rot of Cassava", "scientific_name": "Phytophthora spp.",
     "description": "Water-mold disease causing rotting of root tubers in waterlogged soils.",
     "symptoms": ["wilting of foliage", "leaf dropping", "soft rotten smelly tubers", "root discoloration"],
     "conditions": ["poorly drained waterlogged soils", "heavy clay soils", "heavy rainfall"],
     "severity": "high"},

    # ── Finger Millet Diseases (p9) ──────────
    {"id": "d56", "plant_id": "p9", "name": "Finger Millet Blast", "scientific_name": "Magnaporthe grisea",
     "description": "Most destructive disease of finger millet affecting leaves, neck, and fingers.",
     "symptoms": ["spindle-shaped grey lesions on leaves", "brown discoloration at neck base", "fingers turn brown and shrivel", "grain loss"],
     "conditions": ["high relative humidity", "frequent light showers", "excessive nitrogen application"],
     "severity": "critical"},
    {"id": "d57", "plant_id": "p9", "name": "Brown Spot of Millet", "scientific_name": "Bipolaris nodulosa",
     "description": "Fungal disease causing spotting on leaves, leaf sheaths, and grains.",
     "symptoms": ["small oval brown spots on leaves", "spots merge to form patches", "grain shrivelling", "seedling blight"],
     "conditions": ["nutrient-depleted soils", "warm humid weather", "infected seeds"],
     "severity": "high"},
    {"id": "d58", "plant_id": "p9", "name": "Smut", "scientific_name": "Melanopsichium eleusinis",
     "description": "Fungal disease transforming grains into black gall-like spore balls.",
     "symptoms": ["grains replaced by green-black galls", "black powdery mass when ruptured", "affects individual spikes", "stunted earheads"],
     "conditions": ["high humidity during heading", "moderate temperature 20-25C", "wind dispersion"],
     "severity": "medium"},
    {"id": "d59", "plant_id": "p9", "name": "Seedling Blight", "scientific_name": "Helminthosporium nodulosum",
     "description": "Seed-borne fungal disease causing seedling death and crop failure in nurseries.",
     "symptoms": ["brown spots on seedling leaves", "collar rot at stem base", "seedling collapse", "damping-off symptoms"],
     "conditions": ["high soil moisture", "poor aeration", "infected seeds"],
     "severity": "high"},
    {"id": "d60", "plant_id": "p9", "name": "Banded Blight", "scientific_name": "Rhizoctonia solani",
     "description": "Fungal disease causing irregular straw-coloured patches on leaf sheaths.",
     "symptoms": ["large irregular greyish-white spots", "banded appearance on leaf sheath", "sheath rotting", "culm lodging"],
     "conditions": ["dense crop stand", "high humidity near soil", "nitrogen over-fertilization"],
     "severity": "medium"},

    # ── Coconut Diseases (p10) ───────────────
    {"id": "d61", "plant_id": "p10", "name": "Bud Rot", "scientific_name": "Phytophthora palmivora",
     "description": "Fatal oomycete disease causing decay of the central bud/spindle leaf.",
     "symptoms": ["yellowing of spindle leaf", "spindle leaf rots and collapses", "foul smell from bud center", "crown drops off completely"],
     "conditions": ["heavy monsoon rains", "high relative humidity above 90%", "dense palms block wind"],
     "severity": "critical"},
    {"id": "d62", "plant_id": "p10", "name": "Stem Bleeding", "scientific_name": "Ceratocystis paradoxa",
     "description": "Fungal disease causing dark reddish-brown liquid to ooze from stem cracks.",
     "symptoms": ["reddish-brown fluid oozing from stem cracks", "fluid turns black as it dries", "hollowing of stem interior", "reduced leaf size"],
     "conditions": ["poor drainage", "waterlogging", "heavy nitrogen application"],
     "severity": "high"},
    {"id": "d63", "plant_id": "p10", "name": "Red Ring Disease", "scientific_name": "Bursaphelenchus cocophilus",
     "description": "Nematode-induced disease causing a distinct red ring inside the palm stem.",
     "symptoms": ["yellowing of leaf tips", "leaves turn brown and drop", "distinct red ring inside stem cross-section", "sudden tree decline"],
     "conditions": ["coconut weevil vector activity", "sandy soils", "poor plantation sanitation"],
     "severity": "critical"},
    {"id": "d64", "plant_id": "p10", "name": "Leaf Rot", "scientific_name": "Colletotrichum gloeosporioides",
     "description": "Fungal disease causing blackening and rotting of leaflet tips in young leaves.",
     "symptoms": ["leaflet tips turn dark brown", "leaves look burnt or shredded", "rotten spots on young leaves", "stunted growth"],
     "conditions": ["humidity during monsoon", "insect pest injury", "poor palm nutrition"],
     "severity": "medium"},
    {"id": "d65", "plant_id": "p10", "name": "Root Wilt Disease", "scientific_name": "Phytoplasma",
     "description": "Systemic disease causing flaccidity, yellowing, and necrosis of leaflets.",
     "symptoms": ["bending of leaflets (flaccidity)", "yellowing of leaves from outer whorl", "necrosis on leaflet margins", "root decay"],
     "conditions": ["lace bug vector activity", "laterite soils", "neglected palm nutrition"],
     "severity": "high"},

    # ── Green Gram Diseases (p11) ─────────────
    {"id": "d66", "plant_id": "p11", "name": "Yellow Mosaic Virus", "scientific_name": "Mungbean yellow mosaic virus (MYMV)",
     "description": "Severe viral disease causing bright yellow patches on leaves.",
     "symptoms": ["bright yellow spots on leaves", "complete yellowing of leaves", "stunted plant growth", "reduced pod size"],
     "conditions": ["high whitefly population", "monoculture crop", "dry hot weather"],
     "severity": "critical"},
    {"id": "d67", "plant_id": "p11", "name": "Powdery Mildew", "scientific_name": "Erysiphe polygoni",
     "description": "Fungal disease leaving white powdery patches on leaves.",
     "symptoms": ["white powdery spots on leaf surface", "leaf yellowing", "premature leaf fall", "stunted pods"],
     "conditions": ["moderate temperature 20-25C", "high humidity mornings", "dry days"],
     "severity": "medium"},
    {"id": "d68", "plant_id": "p11", "name": "Cercospora Leaf Spot", "scientific_name": "Cercospora canescens",
     "description": "Fungal leaf spot disease causing brown lesions with grey centers.",
     "symptoms": ["circular brown spots on leaves", "greyish center with reddish border", "defoliation", "reduced pod yield"],
     "conditions": ["warm wet weather", "humidity above 80%", "dense cropping"],
     "severity": "medium"},
    {"id": "d69", "plant_id": "p11", "name": "Root Rot", "scientific_name": "Rhizoctonia solani",
     "description": "Soil-borne fungal rot causing dark brown lesions on stem base.",
     "symptoms": ["dark lesions on stem base", "wilting of foliage", "root decay", "sudden plant death"],
     "conditions": ["waterlogged soil", "poor soil aeration", "high temperature"],
     "severity": "high"},
    {"id": "d70", "plant_id": "p11", "name": "Anthracnose", "scientific_name": "Colletotrichum lindemuthianum",
     "description": "Fungal disease causing dark sunken lesions on leaves and pods.",
     "symptoms": ["dark sunken spots on pods", "reddish-brown veins on leaves", "pod twisting", "seed rot"],
     "conditions": ["cool wet weather", "poor air circulation", "infected seed use"],
     "severity": "high"},

    # ── Okra Diseases (p12) ──────────────────
    {"id": "d71", "plant_id": "p12", "name": "Yellow Vein Mosaic Virus", "scientific_name": "Bhendi yellow vein mosaic virus",
     "description": "Most devastating okra disease causing yellowing of veins.",
     "symptoms": ["yellowing of leaf veins", "entire leaf turning yellow-white", "deformed green-yellow pods", "stunted plants"],
     "conditions": ["whitefly infestation", "monoculture fields", "warm dry weather"],
     "severity": "critical"},
    {"id": "d72", "plant_id": "p12", "name": "Powdery Mildew", "scientific_name": "Erysiphe cichoracearum",
     "description": "White powdery fungal growth on leaves and stems.",
     "symptoms": ["white powdery coating on leaf surface", "leaf curling", "drying of foliage", "reduced fruit production"],
     "conditions": ["warm dry days", "cool humid nights", "shady field areas"],
     "severity": "medium"},
    {"id": "d73", "plant_id": "p12", "name": "Cercospora Leaf Spot", "scientific_name": "Cercospora abelmoschi",
     "description": "Fungal disease causing brown necrotic spots on leaves.",
     "symptoms": ["sooty black-brown leaf spots", "leaf yellowing", "premature leaf fall", "reduced photosynthetic capacity"],
     "conditions": ["high humidity", "rainy season", "unweeded dense crops"],
     "severity": "medium"},
    {"id": "d74", "plant_id": "p12", "name": "Fusarium Wilt", "scientific_name": "Fusarium oxysporum f. sp. vasinfectum",
     "description": "Soil-borne fungal wilt blocking vascular systems.",
     "symptoms": ["wilting of foliage", "yellowing of lower leaves", "brown discoloration in stem cross section", "stunted growth"],
     "conditions": ["warm soil above 26C", "acidic soil", "poor drainage"],
     "severity": "high"},
    {"id": "d75", "plant_id": "p12", "name": "Damping Off", "scientific_name": "Pythium spp.",
     "description": "Fungal rot causing nursery seedling collapse.",
     "symptoms": ["seedling stem constriction at soil line", "seedling collapse", "brown soft root rot", "pre-emergence seed rot"],
     "conditions": ["overwatering", "heavy clay nursery soil", "dense sowing"],
     "severity": "high"},

    # ── Cowpea Diseases (p13) ─────────────────
    {"id": "d76", "plant_id": "p13", "name": "Ashy Stem Blight", "scientific_name": "Macrophomina phaseolina",
     "description": "Fungal disease causing ash-coloured stem cankers.",
     "symptoms": ["dark greyish-ash lesions on stem base", "canker spots", "premature leaf drop", "sudden plant wilting"],
     "conditions": ["hot dry weather", "drought stress", "temperature above 30C"],
     "severity": "high"},
    {"id": "d77", "plant_id": "p13", "name": "Rust", "scientific_name": "Uromyces phaseoli",
     "description": "Fungal disease forming powdery rust-coloured pustules.",
     "symptoms": ["small reddish-brown powdery pustules", "yellow halo around pustules", "defoliation", "shrivelled pods"],
     "conditions": ["cool morning dew", "high humidity above 85%", "moderate temperatures"],
     "severity": "high"},
    {"id": "d78", "plant_id": "p13", "name": "Mosaic Virus", "scientific_name": "Cowpea aphid-borne mosaic virus",
     "description": "Viral disease causing mottled leaf patterns and distortion.",
     "symptoms": ["green and yellow mosaic patterns", "leaf distortion", "stunted growth", "fewer pods"],
     "conditions": ["aphid vectors activity", "diseased seed source", "warm seasons"],
     "severity": "high"},
    {"id": "d79", "plant_id": "p13", "name": "Cercospora Leaf Spot", "scientific_name": "Cercospora cruenta",
     "description": "Fungal leaf spots causing necrotic lesions on foliage.",
     "symptoms": ["reddish-brown circular spots", "ashy grey centers", "premature leaf drop", "stunted growth"],
     "conditions": ["wet warm weather", "poor air circulation", "dense canopy"],
     "severity": "medium"},
    {"id": "d80", "plant_id": "p13", "name": "Root Rot", "scientific_name": "Fusarium solani",
     "description": "Soil-borne root rot causing plant stunting and decay.",
     "symptoms": ["reddish-brown discoloration on taproot", "taproot decay", "stunted plants", "yellowing foliage"],
     "conditions": ["compacted soils", "poor drainage", "continuous legume cropping"],
     "severity": "high"},

    # ── Bitter Gourd Diseases (p14) ───────────
    {"id": "d81", "plant_id": "p14", "name": "Downy Mildew", "scientific_name": "Pseudoperonospora cubensis",
     "description": "Fungal disease leaving angular yellow spots on upper leaves.",
     "symptoms": ["angular yellow leaf spots", "purplish-grey mold under leaf", "leaves turn brown and papery", "stunted growth"],
     "conditions": ["cool humid weather", "dew or rain", "overcrowded vines"],
     "severity": "critical"},
    {"id": "d82", "plant_id": "p14", "name": "Powdery Mildew", "scientific_name": "Sphaerotheca fuliginea",
     "description": "Fungal disease showing white talcum-like powder on foliage.",
     "symptoms": ["white powdery spots on vines and leaves", "yellowing leaves", "premature defoliation", "sunburned fruit"],
     "conditions": ["warm dry weather", "high morning humidity", "shady spots"],
     "severity": "medium"},
    {"id": "d83", "plant_id": "p14", "name": "Bitter Gourd Mosaic", "scientific_name": "Bitter gourd mosaic virus",
     "description": "Viral infection causing leaf mottling and puckering.",
     "symptoms": ["light and dark green mottling", "wrinkled puckered leaves", "deformed small bitter fruit", "reduced vine vigour"],
     "conditions": ["active aphid vector", "infected weed hosts nearby", "mechanical propagation"],
     "severity": "medium"},
    {"id": "d84", "plant_id": "p14", "name": "Alternaria Leaf Spot", "scientific_name": "Alternaria cucumerina",
     "description": "Fungal disease causing concentric target spots on foliage.",
     "symptoms": ["circular brown spots with target rings", "spots merge to form large dead patches", "leaf rolling", "shrivelled fruit"],
     "conditions": ["wet warm weather", "splashing water", "frequent dews"],
     "severity": "medium"},
    {"id": "d85", "plant_id": "p14", "name": "Anthracnose", "scientific_name": "Colletotrichum lagenarium",
     "description": "Fungal disease causing circular water-soaked leaf and fruit lesions.",
     "symptoms": ["water-soaked leaf spots", "sunken circular lesions on fruit", "pink spore masses in wet weather", "vine girdling"],
     "conditions": ["high humidity", "splashing rain", "warm temperatures"],
     "severity": "high"},

    # ── Sweet Potato Diseases (p15) ───────────
    {"id": "d86", "plant_id": "p15", "name": "Feathery Mottle Virus", "scientific_name": "Sweet potato feathery mottle virus",
     "description": "Common viral disease causing feathery purple ring spots.",
     "symptoms": ["purple feathery patterns along leaf veins", "faint green chlorosis", "cracking of tuber skins", "reduced storage life"],
     "conditions": ["active aphid vectors", "untested vine cutting sources", "warm weather"],
     "severity": "medium"},
    {"id": "d87", "plant_id": "p15", "name": "Scurf", "scientific_name": "Monilochaetes infuscans",
     "description": "Fungal infection causing dark brown/black skin discoloration of tubers.",
     "symptoms": ["dark brown to black skin spots on tubers", "shrivelled storage tubers", "unaffected vine growth", "skin discoloration"],
     "conditions": ["soils high in organic matter", "excessive soil moisture", "infected seed tubers"],
     "severity": "medium"},
    {"id": "d88", "plant_id": "p15", "name": "Black Rot", "scientific_name": "Ceratocystis fimbriata",
     "description": "Fungal decay causing black circular lesions on tubers.",
     "symptoms": ["circular black sunken lesions on tubers", "bitter taste in cooked tubers", "black lesions on stem cuttings", "cutting rot"],
     "conditions": ["wet soil", "harvest wounds", "poor storage hygiene"],
     "severity": "high"},
    {"id": "d89", "plant_id": "p15", "name": "Stem Canker", "scientific_name": "Fusarium oxysporum",
     "description": "Soil-borne fungus causing vascular discoloration and cankers.",
     "symptoms": ["yellowing of foliage", "stem splitting and cankers near soil", "vascular browning in stem base", "tuber dry rot"],
     "conditions": ["soil temperatures above 25C", "drought stress", "mechanical weeding injury"],
     "severity": "high"},
    {"id": "d90", "plant_id": "p15", "name": "Soil Rot", "scientific_name": "Streptomyces ipomoeae",
     "description": "Bacterial disease causing pits and lesions on root tubers.",
     "symptoms": ["black dry pits on tubers", "dumbbell-shaped deformed tubers", "stunted yellow vines", "fibrous root decay"],
     "conditions": ["dry soil during tuber initiation", "soil pH above 5.2", "continuous sweet potato crop"],
     "severity": "high"},

    # ── Peanut Diseases (p16) ─────────────────
    {"id": "d91", "plant_id": "p16", "name": "Tikka Leaf Spot", "scientific_name": "Cercospora arachidicola",
     "description": "Fungal leaf spot causing dark circular spots on foliage.",
     "symptoms": ["circular dark brown spots", "yellow halo around spots", "premature leaf fall", "stunted pod filling"],
     "conditions": ["high humidity above 85%", "prolonged leaf wetness", "warm temperatures"],
     "severity": "medium"},
    {"id": "d92", "plant_id": "p16", "name": "Rust", "scientific_name": "Puccinia arachidis",
     "description": "Fungal disease forming orange-brown pustules on leaf undersides.",
     "symptoms": ["pustules on leaf lower surface", "leaves turn brown and dry", "leaf rolling", "premature defoliation"],
     "conditions": ["high relative humidity", "cloudy wet weather", "warm days"],
     "severity": "high"},
    {"id": "d93", "plant_id": "p16", "name": "Stem Rot", "scientific_name": "Sclerotium rolfsii",
     "description": "Soil-borne fungal disease rotting stem bases and pegs.",
     "symptoms": ["white fan-like mycelial growth at stem base", "wilting of individual branches", "rot of pegs and pods", "brown sclerotia seeds"],
     "conditions": ["high soil temperature", "excessive soil moisture", "dense plant canopy"],
     "severity": "high"},
    {"id": "d94", "plant_id": "p16", "name": "Collar Rot", "scientific_name": "Aspergillus niger",
     "description": "Fungal rot affecting seedlings and crown stems.",
     "symptoms": ["black powdery spore masses on collar", "rotting of hypocotyl", "wilting and seedling death", "crown rot"],
     "conditions": ["high soil temperature", "dry soil conditions", "seed injury"],
     "severity": "high"},
    {"id": "d95", "plant_id": "p16", "name": "Bud Necrosis", "scientific_name": "Peanut bud necrosis virus (PBNV)",
     "description": "Thrips-transmitted viral disease causing leaf necrosis and terminal bud death.",
     "symptoms": ["chlorotic ring spots on young leaves", "necrosis of terminal bud", "stunted plant growth", "deformed shrivelled seeds"],
     "conditions": ["high thrips insect population", "late sowing", "weed hosts nearby"],
     "severity": "critical"},

    # ── Black Gram Diseases (p17) ──────────────
    {"id": "d96", "plant_id": "p17", "name": "Yellow Mosaic Virus", "scientific_name": "Mungbean yellow mosaic virus",
     "description": "Severe viral disease causing yellow mosaic patterns on leaves.",
     "symptoms": ["yellow spots on green leaves", "complete yellowing of foliage", "stunted plants", "fewer deformed pods"],
     "conditions": ["whitefly vector activity", "monoculture cropping", "warm dry weather"],
     "severity": "critical"},
    {"id": "d97", "plant_id": "p17", "name": "Powdery Mildew", "scientific_name": "Erysiphe polygoni",
     "description": "Fungal disease covering leaves with white powdery dust.",
     "symptoms": ["white powdery spots on leaf surface", "leaf curling", "drying of foliage", "reduced pod yield"],
     "conditions": ["cool humid mornings", "dry warm days", "high crop density"],
     "severity": "medium"},
    {"id": "d98", "plant_id": "p17", "name": "Leaf Crinkle Virus", "scientific_name": "Urdbean leaf crinkle virus",
     "description": "Viral infection causing leaf puckering and enlargement.",
     "symptoms": ["crinkling of leaves", "enlargement of leaves", "deformed flower parts", "reduced pod setting"],
     "conditions": ["aphid vectors presence", "infected seed use", "warm seasons"],
     "severity": "high"},
    {"id": "d99", "plant_id": "p17", "name": "Root Rot", "scientific_name": "Macrophomina phaseolina",
     "description": "Soil-borne fungus causing dark root decay and plant wilting.",
     "symptoms": ["dark brown lesions on root base", "shredding of bark at stem base", "yellowing and wilting of leaves", "root decay"],
     "conditions": ["high soil temperature above 30C", "drought stress", "poor soil aeration"],
     "severity": "high"},
    {"id": "d100", "plant_id": "p17", "name": "Anthracnose", "scientific_name": "Colletotrichum dematium",
     "description": "Fungal disease causing sunken brown spots on leaves and pods.",
     "symptoms": ["sunken brown spots on pods", "dark spots along leaf veins", "seed staining", "premature leaf fall"],
     "conditions": ["high humidity above 80%", "frequent rains", "use of infected seeds"],
     "severity": "medium"},

    # ── Soybean Diseases (p18) ────────────────
    {"id": "d101", "plant_id": "p18", "name": "Soybean Rust", "scientific_name": "Phakopsora pachyrhizi",
     "description": "Aggressive fungal rust causing rapid defoliation.",
     "symptoms": ["small greyish-brown pustules on leaf underside", "leaf yellowing", "early leaf drop", "underdeveloped seeds"],
     "conditions": ["prolonged leaf wetness", "cool humid weather", "dense crop canopy"],
     "severity": "critical"},
    {"id": "d102", "plant_id": "p18", "name": "Charcoal Rot", "scientific_name": "Macrophomina phaseolina",
     "description": "Soil-borne fungal rot causing grey-black stem discoloration.",
     "symptoms": ["grey-black discoloration of stem base", "loss of root vigor", "wilting under hot sun", "tiny black sclerotia in stem tissues"],
     "conditions": ["low soil moisture", "high temperature above 30C", "soil compaction"],
     "severity": "high"},
    {"id": "d103", "plant_id": "p18", "name": "Yellow Mosaic Virus", "scientific_name": "Soybean yellow mosaic virus",
     "description": "Viral disease causing mottled yellow patterns on leaves.",
     "symptoms": ["yellow speckles on leaves", "leaf mosaic patterns", "stunted plants", "poor pod filling"],
     "conditions": ["whitefly insect presence", "monoculture cropping", "warm seasons"],
     "severity": "high"},
    {"id": "d104", "plant_id": "p18", "name": "Frog Eye Leaf Spot", "scientific_name": "Cercospora sojina",
     "description": "Fungal leaf spot causing circular grey lesions with purplish borders.",
     "symptoms": ["grey circular spots on leaves", "purple-brown borders around spots", "leaf drying", "spotting on pods"],
     "conditions": ["warm wet weather", "humidity above 80%", "surface irrigation splash"],
     "severity": "medium"},
    {"id": "d105", "plant_id": "p18", "name": "Pod and Stem Blight", "scientific_name": "Diaporthe phaseolorum",
     "description": "Fungal blight causing linear rows of black pycnidia on stems and pods.",
     "symptoms": ["linear rows of black dots on stem", "molded shrivelled seeds", "premature stem death", "dark pod lesions"],
     "conditions": ["high humidity during pod maturity", "warm rainy weather", "delayed harvest"],
     "severity": "medium"},

    # ── Maize Diseases (p19) ──────────────────
    {"id": "d106", "plant_id": "p19", "name": "Turcicum Leaf Blight", "scientific_name": "Exserohilum turcicum",
     "description": "Fungal leaf disease causing long cigar-shaped lesions.",
     "symptoms": ["long cigar-shaped greyish-green lesions", "lesions turn straw-coloured", "premature leaf drying", "reduced cob yield"],
     "conditions": ["cool humid weather", "heavy dews", "susceptible hybrids"],
     "severity": "high"},
    {"id": "d107", "plant_id": "p19", "name": "Maydis Leaf Blight", "scientific_name": "Bipolaris maydis",
     "description": "Fungal disease producing small rectangular leaf spots.",
     "symptoms": ["small rectangular brown spots between veins", "spots merge to cover leaves", "cob rot in wet weather", "stalk rot"],
     "conditions": ["warm wet weather", "high relative humidity", "splashing rains"],
     "severity": "medium"},
    {"id": "d108", "plant_id": "p19", "name": "Common Rust", "scientific_name": "Puccinia sorghi",
     "description": "Fungal disease causing golden-brown powdery pustules.",
     "symptoms": ["powdery golden-brown pustules on both leaf sides", "chlorosis", "leaf death in severe cases", "stunted growth"],
     "conditions": ["cool temperatures 16-23C", "high relative humidity", "excessive nitrogen application"],
     "severity": "medium"},
    {"id": "d109", "plant_id": "p19", "name": "Charcoal Rot", "scientific_name": "Macrophomina phaseolina",
     "description": "Fungal stalk rot causing greyish discoloration and shredding of stems.",
     "symptoms": ["wilting of plant at dough stage", "grey stalk base", "shredded internal stalk fibers", "lodging of maize stalks"],
     "conditions": ["high soil temperature above 32C", "drought stress after flowering", "sandy soils"],
     "severity": "high"},
    {"id": "d110", "plant_id": "p19", "name": "Dwarf Mosaic Virus", "scientific_name": "Maize dwarf mosaic virus (MDMV)",
     "description": "Aphid-transmitted virus causing leaf mottling and dwarfing.",
     "symptoms": ["mottling of light and dark green on leaves", "stunted plant internodes", "poor cob filling", "deformed tassel"],
     "conditions": ["high aphid activity", "late planting", "nearby johnsongrass weed hosts"],
     "severity": "medium"},

    # ── Pearl Millet Diseases (p20) ───────────
    {"id": "d111", "plant_id": "p20", "name": "Downy Mildew", "scientific_name": "Sclerospora graminicola",
     "description": "Systemic fungal infection converting panicles into leafy green ear-like structures.",
     "symptoms": ["leaf yellowing and white downy growth below", "conversion of earhead into leafy structure (green ear)", "stunted plant growth", "drying of leaves"],
     "conditions": ["cool wet soil during germination", "humidity above 90%", "temperatures below 25C"],
     "severity": "critical"},
    {"id": "d112", "plant_id": "p20", "name": "Ergot", "scientific_name": "Claviceps fusiformis",
     "description": "Fungal infection producing pink sticky fluid (honey dew) on panicles, turning into black sclerotia.",
     "symptoms": ["pink sticky liquid dripping from florets", "black hard sclerotia replacing grains", "florets fail to seed", "poisonous to livestock"],
     "conditions": ["high relative humidity during flowering", "drizzling rain", "temperatures 20-25C"],
     "severity": "high"},
    {"id": "d113", "plant_id": "p20", "name": "Smut", "scientific_name": "Moesziomyces penicillariae",
     "description": "Fungal disease replacing grains with large green-black spore sacs.",
     "symptoms": ["large green-black sori replacing grains", "spore sacs rupture releasing black powder", "reduced grain count", "stunted panicles"],
     "conditions": ["high humidity", "rain during flowering", "poor crop rotation"],
     "severity": "medium"},
    {"id": "d114", "plant_id": "p20", "name": "Rust", "scientific_name": "Puccinia substriata",
     "description": "Fungal leaf rust causing reddish-brown pustules on foliage.",
     "symptoms": ["reddish-brown powdery pustules on leaves", "leaf chlorosis", "early leaf drying", "reduced forage quality"],
     "conditions": ["cool temperatures", "high morning humidity", "late-sown crops"],
     "severity": "medium"},
    {"id": "d115", "plant_id": "p20", "name": "Blast", "scientific_name": "Pyricularia grisea",
     "description": "Fungal leaf blast producing spindle-shaped lesions.",
     "symptoms": ["spindle-shaped spots with grey centers and brown borders", "leaf drying", "panicle stalk break", "poor grain filling"],
     "conditions": ["high relative humidity", "frequent leaf wetness", "high nitrogen application"],
     "severity": "high"},

    # ── Sorghum Diseases (p21) ────────────────
    {"id": "d116", "plant_id": "p21", "name": "Grain Smut", "scientific_name": "Sphacelotheca sorghi",
     "description": "Fungal disease replacing grain kernels with grey spore sacs.",
     "symptoms": ["grey oval sacs replacing grains", "black powdery mass inside sacs", "deformed panicles", "grain loss"],
     "conditions": ["cool dry soil during sowing", "infected seeds usage", "lack of seed dressing"],
     "severity": "high"},
    {"id": "d117", "plant_id": "p21", "name": "Anthracnose", "scientific_name": "Colletotrichum graminicola",
     "description": "Fungal disease causing circular leaf lesions and red rot of stems.",
     "symptoms": ["circular leaf spots with red-black margins", "red discoloration inside stems (stalk rot)", "lodging of stalks", "poor grain fill"],
     "conditions": ["warm wet weather", "humidity above 85%", "continuous sorghum crops"],
     "severity": "high"},
    {"id": "d118", "plant_id": "p21", "name": "Charcoal Rot", "scientific_name": "Macrophomina phaseolina",
     "description": "Soil-borne fungal rot causing internal stem fiber shredding.",
     "symptoms": ["premature plant drying", "stalk base lodging", "pith of stem turns charcoal-black", "poor panicle fill"],
     "conditions": ["drought stress during grain fill", "soil temperature above 32C", "low soil moisture"],
     "severity": "high"},
    {"id": "d119", "plant_id": "p21", "name": "Downy Mildew", "scientific_name": "Peronosclerospora sorghi",
     "description": "Systemic downy mildew causing leaf striping and stunting.",
     "symptoms": ["yellow-green linear stripes on leaves", "white downy growth on leaf lower sides", "shredded leaf margins", "sterile panicles"],
     "conditions": ["cool humid weather after sowing", "soil temperature 20-24C", "poor drainage"],
     "severity": "high"},
    {"id": "d120", "plant_id": "p21", "name": "Leaf Blight", "scientific_name": "Exserohilum turcicum",
     "description": "Fungal blight causing long dry lesions on sorghum foliage.",
     "symptoms": ["large long dry straw-coloured spots", "purple margins around spots", "early leaf death", "reduced crop fodder value"],
     "conditions": ["cool wet weather", "heavy dews during crop growth", "poor nitrogen soils"],
     "severity": "medium"},

    # ── Foxtail Millet Diseases (p22) ──────────
    {"id": "d121", "plant_id": "p22", "name": "Foxtail Millet Blast", "scientific_name": "Pyricularia setariae",
     "description": "Fungal blast disease causing leaf and panicle lesions.",
     "symptoms": ["spindle-shaped grey lesions on leaves", "panicle base rot (neck blast)", "grain shrivelling", "premature lodging"],
     "conditions": ["high humidity", "over-fertilization of nitrogen", "cloudy wet weather"],
     "severity": "high"},
    {"id": "d122", "plant_id": "p22", "name": "Downy Mildew", "scientific_name": "Sclerospora graminicola",
     "description": "Fungal disease causing leaf chlorosis and green ear conversion.",
     "symptoms": ["leaf yellowing and linear streaks", "leaf shredding", "earhead turns green leafy", "poor seed yield"],
     "conditions": ["humid soils", "moderate temperatures", "diseased crop debris on surface"],
     "severity": "high"},
    {"id": "d123", "plant_id": "p22", "name": "Smut", "scientific_name": "Ustilago crameri",
     "description": "Fungal infection converting seeds into black spore powders.",
     "symptoms": ["grain kernels replaced by dark spore masses", "black dust released at wind", "stunted earheads", "severe grain loss"],
     "conditions": ["dry soil during germination", "un-treated seeds", "acidic soil"],
     "severity": "high"},
    {"id": "d124", "plant_id": "p22", "name": "Rust", "scientific_name": "Uromyces setariae-italicae",
     "description": "Fungal foliage rust producing powdery spots.",
     "symptoms": ["tiny brown powdery spots on leaves", "leaf yellowing", "premature leaf dry", "reduced plant fodder quality"],
     "conditions": ["cool morning dew", "humid days", "dense crop spacing"],
     "severity": "medium"},
    {"id": "d125", "plant_id": "p22", "name": "Seedling Blight", "scientific_name": "Pythium debaryanum",
     "description": "Soil-borne fungal rot attacking young seedling roots.",
     "symptoms": ["seedling stem collapse at soil line", "brown watery roots", "patchy nursery emergence", "damp stem rot"],
     "conditions": ["wet waterlogged soil", "clay soil", "cold soil temperatures"],
     "severity": "high"},

    # ── Gotukola Diseases (p23) ───────────────
    {"id": "d126", "plant_id": "p23", "name": "Gotukola Leaf Spot", "scientific_name": "Cercospora centellae",
     "description": "Fungal leaf spot causing cosmetic damage to leafy herb.",
     "symptoms": ["circular brown spots on leaves", "grey leaf spots centers", "yellowing around lesions", "unmarketable leaves"],
     "conditions": ["excessive overhead irrigation", "high crop density", "warm humid days"],
     "severity": "high"},
    {"id": "d127", "plant_id": "p23", "name": "Root Rot", "scientific_name": "Rhizoctonia solani",
     "description": "Soil-borne fungal rot decaying runner roots.",
     "symptoms": ["yellowing of leaf clusters", "brown rotted runner roots", "wilting patches in bed", "stunted leaf regrowth"],
     "conditions": ["poor soil drainage", "overwatering", "heavy clay soil beds"],
     "severity": "high"},
    {"id": "d128", "plant_id": "p23", "name": "Gotukola Wilt", "scientific_name": "Fusarium oxysporum",
     "description": "Soil-borne fungal wilt causing permanent collapse of runners.",
     "symptoms": ["yellowing of runners foliage", "wilting under noon sun", "brown vascular rings in stems", "sudden plant death"],
     "conditions": ["warm soil temperature", "acidic soil bed", "continuous herb planting"],
     "severity": "high"},
    {"id": "d129", "plant_id": "p23", "name": "Collar Rot", "scientific_name": "Sclerotium rolfsii",
     "description": "Soil-borne fungus rotting stem bases and runner nodes.",
     "symptoms": ["white cottony mold at runner nodes", "rotting of stems at soil contact", "wilting patches", "small round mustard-like sclerotia"],
     "conditions": ["high soil temperature", "high humidity near soil", "heavy organic litter"],
     "severity": "high"},
    {"id": "d130", "plant_id": "p23", "name": "Mosaic Virus", "scientific_name": "Centella mosaic virus",
     "description": "Viral infection causing puckered leaves and light green mosaic.",
     "symptoms": ["light and dark green mottling", "deformed wrinkled small leaves", "slow runner propagation", "chlorotic spots"],
     "conditions": ["aphid vectors presence", "propagation of infected runners", "weedy field borders"],
     "severity": "medium"},

    # ── Spinach Diseases (p24) ────────────────
    {"id": "d131", "plant_id": "p24", "name": "Downy Mildew", "scientific_name": "Peronospora farinosa",
     "description": "Fungal disease causing yellow patches on leaves with blue-grey downy underside.",
     "symptoms": ["dull yellow angular patches on upper leaf", "blue-grey fuzzy mold on leaf underside", "leaf distortion", "curled unmarketable leaves"],
     "conditions": ["cool wet weather", "overhead sprinkler irrigation", "dew or rain wetness"],
     "severity": "high"},
    {"id": "d132", "plant_id": "p24", "name": "White Rust", "scientific_name": "Albugo occidentalis",
     "description": "Fungal-like oomycete disease causing white blisters on leaf undersides.",
     "symptoms": ["white chalky blisters on lower leaf surface", "yellow spots on upper leaf surface", "leaf drying", "complete crop spoilage"],
     "conditions": ["cool wet nights", "warm dry days", "dense plant spacing"],
     "severity": "high"},
    {"id": "d133", "plant_id": "p24", "name": "Cladosporium Leaf Spot", "scientific_name": "Cladosporium variabile",
     "description": "Fungal disease producing small circular olive-green spots.",
     "symptoms": ["small circular spots on leaves", "olive-green to dark brown color on spots", "spots dry and turn papery", "spoilage of leaf harvest"],
     "conditions": ["cool wet conditions", "relative humidity above 85%", "splashing water"],
     "severity": "medium"},
    {"id": "d134", "plant_id": "p24", "name": "Damping Off", "scientific_name": "Pythium ultimum",
     "description": "Fungal rot causing seedling death in seedbed.",
     "symptoms": ["seedling stem collapse at soil line", "water-soaked soft brown roots", "poor patchy germination", "soft rot of seedlings"],
     "conditions": ["sowing too deep", "heavy wet soil", "poor drainage"],
     "severity": "high"},
    {"id": "d135", "plant_id": "p24", "name": "Fusarium Wilt", "scientific_name": "Fusarium oxysporum f. sp. spinaciae",
     "description": "Soil-borne fungal pathogen causing wilting of spinach.",
     "symptoms": ["yellowing of lower leaves", "wilting under hot sun", "brown vascular root core", "stunted leaf regrowth"],
     "conditions": ["warm soil above 24C", "acidic soil", "poor crop rotation"],
     "severity": "high"},

    # ── Beetroot Diseases (p25) ───────────────
    {"id": "d136", "plant_id": "p25", "name": "Cercospora Leaf Spot", "scientific_name": "Cercospora beticola",
     "description": "Fungal leaf spot causing dark circular spots with purple margins.",
     "symptoms": ["circular spots on leaves", "grey centers with purple-red borders", "leaf drying and defoliation", "reduced root size"],
     "conditions": ["high humidity above 80%", "warm temperatures 25-30C", "overhead irrigation"],
     "severity": "high"},
    {"id": "d137", "plant_id": "p25", "name": "Downy Mildew", "scientific_name": "Peronospora farinosa f. sp. betae",
     "description": "Fungal infection curling leaves with grey fuzz below.",
     "symptoms": ["curled thickened young leaves", "grey fuzzy mold on leaf underside", "stunted leaf crown", "small woody beetroot"],
     "conditions": ["cool damp weather", "heavy dew mornings", "poor crop spacing"],
     "severity": "medium"},
    {"id": "d138", "plant_id": "p25", "name": "Scab", "scientific_name": "Streptomyces scabies",
     "description": "Bacterial-like soil pathogen causing corky lesions on beetroot bulbs.",
     "symptoms": ["corky brown patches on beetroot skin", "rough cracked root surface", "unmarketable roots", "stunted root growth"],
     "conditions": ["dry soil during root swelling", "alkaline soil pH above 6.5", "fresh manure use"],
     "severity": "medium"},
    {"id": "d139", "plant_id": "p25", "name": "Curly Top", "scientific_name": "Beet curly top virus (BCTV)",
     "description": "Leafhopper-transmitted virus causing severe foliage distortion.",
     "symptoms": ["upward curling of leaves", "dark swollen leaf veins", "stunted plants", "excessive fibrous lateral roots"],
     "conditions": ["active leafhopper vector", "dry hot weather", "nearby weed hosts"],
     "severity": "high"},
    {"id": "d140", "plant_id": "p25", "name": "Root Rot", "scientific_name": "Rhizoctonia solani",
     "description": "Soil-borne fungal rot causing black decay at root crown.",
     "symptoms": ["black decay on beetroot neck and crown", "leaf wilting and drop", "water-soaked soft rot of root bulb", "plant collapse"],
     "conditions": ["heavy soil moisture", "poor drainage", "warm soil temperatures"],
     "severity": "high"},

    # ── Radish Diseases (p26) ─────────────────
    {"id": "d141", "plant_id": "p26", "name": "White Rust", "scientific_name": "Albugo candida",
     "description": "Oomycete causing chalky white pustules on foliage.",
     "symptoms": ["chalky white pustules on lower leaf side", "yellow spots on upper leaf side", "distorted swollen stems", "deformed radish roots"],
     "conditions": ["cool wet mornings", "high relative humidity", "heavy morning dews"],
     "severity": "high"},
    {"id": "d142", "plant_id": "p26", "name": "Alternaria Leaf Spot", "scientific_name": "Alternaria brassicae",
     "description": "Fungal leaf spot causing dark concentric rings.",
     "symptoms": ["dark circular target spots on leaves", "concentric rings in lesions", "shot-hole effect on leaf drying", "black spots on root necks"],
     "conditions": ["wet warm weather", "splashing rains", "dense spacing"],
     "severity": "medium"},
    {"id": "d143", "plant_id": "p26", "name": "Downy Mildew", "scientific_name": "Peronospora parasitica",
     "description": "Fungal disease causing yellow patches on leaves with white fuzz below.",
     "symptoms": ["yellowish-grey angular patches on leaves", "white fuzzy mold below leaf", "brown internal streaks in radish root", "leaf drying"],
     "conditions": ["cool wet weather", "poor air circulation", "splashing irrigation"],
     "severity": "medium"},
    {"id": "d144", "plant_id": "p26", "name": "Clubroot", "scientific_name": "Plasmodiophora brassicae",
     "description": "Soil-borne pathogen causing distorted gall-like root swellings.",
     "symptoms": ["swollen spindle galls on roots", "wilting under hot sun", "stunted plant growth", "decay and rot of radish roots"],
     "conditions": ["acidic soil pH below 6.5", "cool wet soil", "poor crop rotation"],
     "severity": "high"},
    {"id": "d145", "plant_id": "p26", "name": "Fusarium Wilt", "scientific_name": "Fusarium oxysporum f. sp. raphani",
     "description": "Soil-borne fungus causing leaf yellowing and vascular rot.",
     "symptoms": ["yellowing of leaf margins from lower leaves", "wilting of plant foliage", "brown vascular discoloration in radish root", "root stunting"],
     "conditions": ["warm soil above 25C", "poor drainage", "acidic soil"],
     "severity": "high"},

    # ── Yam Diseases (p27) ────────────────────
    {"id": "d146", "plant_id": "p27", "name": "Yam Anthracnose", "scientific_name": "Colletotrichum gloeosporioides",
     "description": "Fungal disease causing leaf scorch and vine dieback.",
     "symptoms": ["circular black-brown spots on leaves", "spots merge causing leaf scorch", "black lesions on vines", "dieback of vine tips"],
     "conditions": ["heavy monsoon rains", "high humidity above 85%", "lack of trellising"],
     "severity": "critical"},
    {"id": "d147", "plant_id": "p27", "name": "Yam Mosaic Virus", "scientific_name": "Yam mosaic virus (YMV)",
     "description": "Viral infection causing green mosaic stripes and leaf deformation.",
     "symptoms": ["light and dark green mosaic on leaves", "deformed narrow leaves", "stunted vine growth", "smaller low-yield tubers"],
     "conditions": ["aphid vectors activity", "propagation of infected seed tubers", "mechanical injuries"],
     "severity": "high"},
    {"id": "d148", "plant_id": "p27", "name": "Dry Rot", "scientific_name": "Pratylenchus coffeae (Nematode)",
     "description": "Nematode-induced rotting of yam storage tubers.",
     "symptoms": ["brown-black cracks on tuber surface", "dry corky decay under tuber skin", "stunted vine growth", "foliar yellowing"],
     "conditions": ["soil high in nematode population", "continuous yam cultivation", "untreated seed tubers"],
     "severity": "high"},
    {"id": "d149", "plant_id": "p27", "name": "Yam Leaf Spot", "scientific_name": "Cercospora dioscoreae",
     "description": "Fungal disease producing brown angular leaf spots.",
     "symptoms": ["angular brown spots on leaves", "yellow leaf margins around lesions", "early leaf drying", "reduced tuber yield"],
     "conditions": ["prolonged wet season", "shade in field", "high density planting"],
     "severity": "medium"},
    {"id": "d150", "plant_id": "p27", "name": "Collar Rot", "scientific_name": "Sclerotium rolfsii",
     "description": "Fungal attack rotting base of yam vines.",
     "symptoms": ["cottony white mold at stem base", "wilting of entire vine", "rotting of yam neck", "tiny round brown sclerotia on soil"],
     "conditions": ["high soil temperature", "excessive soil moisture", "poor drainage beds"],
     "severity": "high"},
]
