# backend/seed/diseases.py
# 40 disease records across 5 crops (8 per crop)

diseases = [
    # ── Tomato Diseases ─────────────────────
    {"id": "d1", "plant_id": "p1", "name": "Early Blight", "scientific_name": "Alternaria solani",
     "description": "Fungal disease causing concentric ring-shaped lesions on older leaves.",
     "symptoms": ["dark concentric rings on leaves", "yellowing around spots", "leaf drop from bottom up", "stem lesions"],
     "conditions": ["high humidity", "warm temperature 24-30C", "overhead irrigation"],
     "severity": "high"},
    {"id": "d2", "plant_id": "p1", "name": "Late Blight", "scientific_name": "Phytophthora infestans",
     "description": "Devastating oomycete disease that can destroy entire crop within days.",
     "symptoms": ["water-soaked grey-green spots", "white fuzzy growth on leaf underside", "fruit turning brown", "rapid wilting"],
     "conditions": ["cool wet weather", "temperature 15-22C", "high humidity above 90%"],
     "severity": "critical"},
    {"id": "d3", "plant_id": "p1", "name": "Bacterial Wilt", "scientific_name": "Ralstonia solanacearum",
     "description": "Soil-borne bacterial disease causing sudden wilting without yellowing.",
     "symptoms": ["sudden wilting of whole plant", "no yellowing before wilt", "brown vascular tissue", "bacterial ooze from cut stem"],
     "conditions": ["warm soil above 25C", "waterlogged conditions", "acidic soil"],
     "severity": "critical"},
    {"id": "d4", "plant_id": "p1", "name": "Fusarium Wilt", "scientific_name": "Fusarium oxysporum",
     "description": "Soil-borne fungus blocking water transport in the plant.",
     "symptoms": ["yellowing of lower leaves on one side", "progressive wilting", "brown discoloration in stem", "stunted growth"],
     "conditions": ["warm soil 27-30C", "acidic soil", "poor drainage"],
     "severity": "high"},
    {"id": "d5", "plant_id": "p1", "name": "Leaf Curl Virus", "scientific_name": "Tomato leaf curl virus (ToLCV)",
     "description": "Viral disease transmitted by whiteflies causing severe leaf deformation.",
     "symptoms": ["upward curling of leaves", "thickened leathery leaves", "stunted growth", "yellow margins"],
     "conditions": ["whitefly infestation", "dry hot weather", "monoculture"],
     "severity": "high"},
    {"id": "d6", "plant_id": "p1", "name": "Blossom End Rot", "scientific_name": None,
     "description": "Physiological disorder caused by calcium deficiency or irregular watering.",
     "symptoms": ["dark sunken patch at fruit bottom", "brown leathery tissue", "affects green and ripe fruits"],
     "conditions": ["irregular watering", "calcium deficiency", "high nitrogen"],
     "severity": "medium"},
    {"id": "d7", "plant_id": "p1", "name": "Powdery Mildew", "scientific_name": "Leveillula taurica",
     "description": "Fungal disease producing white powdery growth on leaf surfaces.",
     "symptoms": ["white powdery patches on leaves", "yellow spots on upper leaf surface", "leaf drying", "reduced photosynthesis"],
     "conditions": ["dry weather", "moderate temperature 20-25C", "poor air circulation"],
     "severity": "medium"},
    {"id": "d8", "plant_id": "p1", "name": "Septoria Leaf Spot", "scientific_name": "Septoria lycopersici",
     "description": "Fungal disease causing numerous small spots on lower leaves.",
     "symptoms": ["small circular spots with dark border", "grey centers with tiny dots", "lower leaf yellowing", "premature defoliation"],
     "conditions": ["wet weather", "splashing rain", "warm temperature"],
     "severity": "medium"},

    # ── Chili Diseases ──────────────────────
    {"id": "d9", "plant_id": "p2", "name": "Anthracnose", "scientific_name": "Colletotrichum capsici",
     "description": "Major post-harvest disease causing sunken lesions on fruits.",
     "symptoms": ["sunken circular spots on fruits", "dark brown to black lesions", "concentric rings on pods", "fruit rotting"],
     "conditions": ["high humidity above 80%", "warm temperature 25-30C", "rain splashing"],
     "severity": "high"},
    {"id": "d10", "plant_id": "p2", "name": "Chili Leaf Curl", "scientific_name": "Chili leaf curl virus",
     "description": "Viral disease causing severe leaf distortion transmitted by whiteflies.",
     "symptoms": ["upward leaf curling", "puckering of leaves", "stunted plant growth", "reduced fruiting"],
     "conditions": ["whitefly vector", "hot dry conditions", "continuous cropping"],
     "severity": "high"},
    {"id": "d11", "plant_id": "p2", "name": "Damping Off", "scientific_name": "Pythium spp.",
     "description": "Soil-borne disease affecting seedlings at nursery stage.",
     "symptoms": ["seedling collapse at soil level", "water-soaked stem base", "pre-emergence seed rot", "thin weak stems"],
     "conditions": ["overwatering", "poor drainage", "dense sowing"],
     "severity": "high"},
    {"id": "d12", "plant_id": "p2", "name": "Cercospora Leaf Spot", "scientific_name": "Cercospora capsici",
     "description": "Fungal disease causing circular spots on chili leaves.",
     "symptoms": ["circular brown spots", "whitish grey center", "leaf yellowing", "premature leaf drop"],
     "conditions": ["humid conditions", "poor ventilation", "continuous cropping"],
     "severity": "medium"},
    {"id": "d13", "plant_id": "p2", "name": "Bacterial Leaf Spot", "scientific_name": "Xanthomonas campestris",
     "description": "Bacterial disease causing water-soaked lesions on leaves and fruits.",
     "symptoms": ["small water-soaked spots", "spots turn brown and necrotic", "raised bumps on fruits", "leaf defoliation"],
     "conditions": ["warm wet conditions", "overhead irrigation", "wind-driven rain"],
     "severity": "medium"},
    {"id": "d14", "plant_id": "p2", "name": "Powdery Mildew", "scientific_name": "Leveillula taurica",
     "description": "White powdery fungal growth on leaves reducing photosynthesis.",
     "symptoms": ["white powdery coating", "yellowing patches", "leaf curling downward", "premature leaf fall"],
     "conditions": ["moderate humidity", "warm days cool nights", "poor airflow"],
     "severity": "medium"},
    {"id": "d15", "plant_id": "p2", "name": "Fusarium Wilt", "scientific_name": "Fusarium oxysporum f.sp. capsici",
     "description": "Soil-borne wilt disease causing vascular browning.",
     "symptoms": ["yellowing lower leaves", "progressive wilting", "brown vascular bundles", "plant death"],
     "conditions": ["warm soil", "acidic pH", "previous Solanaceae crops"],
     "severity": "high"},
    {"id": "d16", "plant_id": "p2", "name": "Fruit Rot", "scientific_name": "Phytophthora capsici",
     "description": "Water mold causing rapid fruit rotting especially after rain.",
     "symptoms": ["water-soaked fruit lesions", "white cottony growth", "rapid fruit decay", "dark brown patches"],
     "conditions": ["standing water", "heavy rainfall", "poor drainage"],
     "severity": "high"},

    # ── Rice Diseases ───────────────────────
    {"id": "d17", "plant_id": "p3", "name": "Blast Disease", "scientific_name": "Magnaporthe oryzae",
     "description": "Most devastating rice disease affecting leaves, nodes, and panicles.",
     "symptoms": ["diamond-shaped grey spots", "white to grey center", "neck blast at panicle base", "grain discoloration"],
     "conditions": ["high nitrogen", "cloudy weather", "temperature 25-28C"],
     "severity": "critical"},
    {"id": "d18", "plant_id": "p3", "name": "Bacterial Leaf Blight", "scientific_name": "Xanthomonas oryzae",
     "description": "Major bacterial disease causing leaf drying from tips.",
     "symptoms": ["yellow to white streaks from leaf tip", "wavy leaf margins", "entire leaf drying", "milky bacterial ooze"],
     "conditions": ["warm humid weather", "flooding", "strong winds with rain"],
     "severity": "high"},
    {"id": "d19", "plant_id": "p3", "name": "Sheath Blight", "scientific_name": "Rhizoctonia solani",
     "description": "Fungal disease causing irregular lesions on leaf sheaths.",
     "symptoms": ["oval greenish-grey lesions on sheath", "lesions merge upward", "lodging", "white powdery surface"],
     "conditions": ["dense planting", "high nitrogen", "warm humid 28-32C"],
     "severity": "high"},
    {"id": "d20", "plant_id": "p3", "name": "Brown Spot", "scientific_name": "Bipolaris oryzae",
     "description": "Fungal disease associated with nutrient deficiency.",
     "symptoms": ["oval brown spots", "grey center", "spots on glumes", "poor grain filling"],
     "conditions": ["nutrient-deficient soil", "drought stress", "poor management"],
     "severity": "medium"},
    {"id": "d21", "plant_id": "p3", "name": "Tungro Virus", "scientific_name": "Rice tungro virus",
     "description": "Viral complex transmitted by green leafhoppers.",
     "symptoms": ["yellow-orange leaf discoloration", "stunted plants", "reduced tillering", "delayed flowering"],
     "conditions": ["leafhopper presence", "early season infection", "susceptible varieties"],
     "severity": "high"},
    {"id": "d22", "plant_id": "p3", "name": "False Smut", "scientific_name": "Ustilaginoidea virens",
     "description": "Fungal disease converting rice grains into large spore balls.",
     "symptoms": ["orange to green spore balls on panicle", "individual grains replaced", "velvety appearance", "reduced yield"],
     "conditions": ["high humidity at flowering", "overcast weather", "high nitrogen"],
     "severity": "medium"},
    {"id": "d23", "plant_id": "p3", "name": "Stem Rot", "scientific_name": "Sclerotium oryzae",
     "description": "Fungal disease causing stem weakening and lodging.",
     "symptoms": ["black lesions at water line", "hollow stems", "premature ripening", "lodging at maturity"],
     "conditions": ["continuous flooding", "high nitrogen", "stubble not decomposed"],
     "severity": "medium"},
    {"id": "d24", "plant_id": "p3", "name": "Grain Discoloration", "scientific_name": "Multiple fungi",
     "description": "Complex of fungi discolouring rice grains, reducing market value.",
     "symptoms": ["dark spots on grains", "chalky grains", "discoloured husks", "reduced milling quality"],
     "conditions": ["wet weather at maturity", "delayed harvest", "insect damage"],
     "severity": "medium"},

    # ── Brinjal Diseases ────────────────────
    {"id": "d25", "plant_id": "p4", "name": "Bacterial Wilt", "scientific_name": "Ralstonia solanacearum",
     "description": "Soil-borne bacterial wilt — most serious brinjal disease in tropics.",
     "symptoms": ["sudden wilting", "no leaf yellowing", "brown vascular tissue", "bacterial streaming in water test"],
     "conditions": ["warm wet soil", "acidic conditions", "previous Solanaceae crop"],
     "severity": "critical"},
    {"id": "d26", "plant_id": "p4", "name": "Phomopsis Blight", "scientific_name": "Phomopsis vexans",
     "description": "Fungal disease causing leaf spots and fruit rot.",
     "symptoms": ["circular leaf spots with concentric rings", "fruit rot with soft brown areas", "stem cankers", "damping off in nursery"],
     "conditions": ["high humidity", "warm temperature", "splashing rain"],
     "severity": "high"},
    {"id": "d27", "plant_id": "p4", "name": "Little Leaf", "scientific_name": "Phytoplasma",
     "description": "Phytoplasma disease causing extreme leaf reduction.",
     "symptoms": ["very small leaves", "excessive branching", "bushy stunted plant", "green flowers"],
     "conditions": ["leafhopper vector", "warm season", "weed hosts nearby"],
     "severity": "high"},
    {"id": "d28", "plant_id": "p4", "name": "Cercospora Leaf Spot", "scientific_name": "Cercospora melongenae",
     "description": "Fungal leaf spot disease of brinjal.",
     "symptoms": ["angular chlorotic spots", "spots turn brown", "shot-hole appearance", "defoliation"],
     "conditions": ["humid weather", "overcrowding", "poor drainage"],
     "severity": "medium"},
    {"id": "d29", "plant_id": "p4", "name": "Verticillium Wilt", "scientific_name": "Verticillium dahliae",
     "description": "Soil-borne fungus causing progressive wilting.",
     "symptoms": ["V-shaped yellowing on leaves", "wilting during hot days", "recovery at night initially", "brown vascular tissue"],
     "conditions": ["cool soil 20-24C", "previously infected soil", "wet conditions"],
     "severity": "high"},
    {"id": "d30", "plant_id": "p4", "name": "Damping Off", "scientific_name": "Pythium spp. / Rhizoctonia spp.",
     "description": "Seedling disease in nursery causing collar rot.",
     "symptoms": ["seedling collapse", "water-soaked stem at soil line", "brown rotting base", "pre-emergence death"],
     "conditions": ["overwatering", "dense sowing", "poor ventilation"],
     "severity": "high"},
    {"id": "d31", "plant_id": "p4", "name": "Powdery Mildew", "scientific_name": "Erysiphe cichoracearum",
     "description": "White powdery fungal growth on brinjal leaves.",
     "symptoms": ["white powdery patches", "yellowing leaves", "leaf curling", "premature defoliation"],
     "conditions": ["dry warm weather", "poor air circulation", "shaded areas"],
     "severity": "medium"},
    {"id": "d32", "plant_id": "p4", "name": "Mosaic Virus", "scientific_name": "Eggplant mosaic virus",
     "description": "Viral disease causing mottled leaf patterns.",
     "symptoms": ["light and dark green mottling", "leaf distortion", "stunted growth", "reduced fruit size"],
     "conditions": ["aphid vectors", "weed reservoirs", "mechanical transmission"],
     "severity": "medium"},

    # ── Beans Diseases ──────────────────────
    {"id": "d33", "plant_id": "p5", "name": "Anthracnose", "scientific_name": "Colletotrichum lindemuthianum",
     "description": "Seed-borne fungal disease causing dark sunken lesions on pods.",
     "symptoms": ["dark sunken spots on pods", "reddish-brown veins on leaves", "pod twisting", "seed discoloration"],
     "conditions": ["cool humid weather", "infected seed", "overhead irrigation"],
     "severity": "high"},
    {"id": "d34", "plant_id": "p5", "name": "Rust", "scientific_name": "Uromyces appendiculatus",
     "description": "Fungal disease producing rusty brown pustules on leaves.",
     "symptoms": ["small reddish-brown pustules", "powdery spores when rubbed", "yellow halo around pustules", "severe defoliation"],
     "conditions": ["warm humid 17-27C", "morning dew", "dense canopy"],
     "severity": "high"},
    {"id": "d35", "plant_id": "p5", "name": "Angular Leaf Spot", "scientific_name": "Phaeoisariopsis griseola",
     "description": "Fungal disease causing angular lesions limited by leaf veins.",
     "symptoms": ["angular grey-brown spots", "lesions bounded by veins", "spots on pods", "premature defoliation"],
     "conditions": ["warm humid weather", "poor air flow", "infected seed"],
     "severity": "medium"},
    {"id": "d36", "plant_id": "p5", "name": "Common Bacterial Blight", "scientific_name": "Xanthomonas axonopodis",
     "description": "Bacterial disease causing water-soaked lesions on leaves.",
     "symptoms": ["water-soaked spots on leaves", "yellow halo around lesions", "brown necrotic patches", "pod lesions"],
     "conditions": ["warm wet weather", "splashing rain", "infected seed"],
     "severity": "medium"},
    {"id": "d37", "plant_id": "p5", "name": "Root Rot", "scientific_name": "Rhizoctonia solani",
     "description": "Soil-borne disease causing root and lower stem rotting.",
     "symptoms": ["reddish-brown lesions on stem base", "wilting plants", "poor root system", "plant death"],
     "conditions": ["waterlogged soil", "compacted soil", "cool wet conditions"],
     "severity": "high"},
    {"id": "d38", "plant_id": "p5", "name": "Bean Mosaic Virus", "scientific_name": "Bean common mosaic virus",
     "description": "Seed-borne viral disease causing leaf mottling.",
     "symptoms": ["green mosaic pattern", "leaf curling downward", "puckered leaves", "stunted pods"],
     "conditions": ["aphid transmission", "infected seed", "warm season"],
     "severity": "medium"},
    {"id": "d39", "plant_id": "p5", "name": "Powdery Mildew", "scientific_name": "Erysiphe polygoni",
     "description": "White powdery fungal growth on bean leaves and pods.",
     "symptoms": ["white powdery growth", "yellowing leaves", "premature leaf drop", "pod surface affected"],
     "conditions": ["dry warm days", "cool nights", "poor ventilation"],
     "severity": "medium"},
    {"id": "d40", "plant_id": "p5", "name": "Halo Blight", "scientific_name": "Pseudomonas syringae pv. phaseolicola",
     "description": "Bacterial disease producing spots with prominent green-yellow halo.",
     "symptoms": ["small water-soaked spots", "large greenish-yellow halo", "systemic yellowing", "cream-coloured bacterial ooze"],
     "conditions": ["cool wet weather", "splashing rain", "seed-borne"],
     "severity": "high"},
]
