# backend/seed/fertilizers.py
# 60 fertilizer recommendation records: ~2 per stage per method (organic/conventional)
# Format: stage_id, farming_method, fertilizer_name, application_rate_per_acre_kg, instructions

fertilizers = [
    # ── Tomato ──────────────────────────────
    {"stage_id": "s2", "farming_method": "conventional", "fertilizer_name": "Starter NPK 10-26-26", "rate": 50, "instructions": "Apply at transplanting as basal dose. Mix well into soil."},
    {"stage_id": "s2", "farming_method": "organic", "fertilizer_name": "Vermicompost", "rate": 200, "instructions": "Mix into planting holes before transplanting seedlings."},
    {"stage_id": "s3", "farming_method": "conventional", "fertilizer_name": "Urea (46-0-0)", "rate": 30, "instructions": "Side-dress 10 cm from stem. Water immediately after."},
    {"stage_id": "s3", "farming_method": "organic", "fertilizer_name": "Blood Meal", "rate": 25, "instructions": "Side-dress around plants. High nitrogen for vegetative growth."},
    {"stage_id": "s3", "farming_method": "conventional", "fertilizer_name": "DAP 18-46-0", "rate": 25, "instructions": "Apply 2nd split dose as top-dressing during active growth."},
    {"stage_id": "s3", "farming_method": "organic", "fertilizer_name": "Fish Emulsion", "rate": 15, "instructions": "Dilute 1:10 with water and drench around root zone weekly."},
    {"stage_id": "s4", "farming_method": "conventional", "fertilizer_name": "MOP (Muriate of Potash)", "rate": 45, "instructions": "Apply at flowering to promote fruit set. Band apply."},
    {"stage_id": "s4", "farming_method": "organic", "fertilizer_name": "Kelp Meal", "rate": 20, "instructions": "Broadcast around plants. Rich in potassium for flowering."},
    {"stage_id": "s4", "farming_method": "conventional", "fertilizer_name": "Calcium Ammonium Nitrate", "rate": 25, "instructions": "Top-dress to prevent blossom end rot during flowering."},
    {"stage_id": "s4", "farming_method": "organic", "fertilizer_name": "Bone Meal", "rate": 30, "instructions": "Work into soil surface. Provides calcium and phosphorus."},
    {"stage_id": "s5", "farming_method": "conventional", "fertilizer_name": "Potassium Sulphate", "rate": 30, "instructions": "Foliar spray or fertigation during fruit development."},
    {"stage_id": "s5", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 40, "instructions": "Broadcast lightly. Do not over-apply; raises pH."},

    # ── Chili ───────────────────────────────
    {"stage_id": "s8", "farming_method": "conventional", "fertilizer_name": "NPK 15-15-15", "rate": 50, "instructions": "Apply as basal dose during transplanting."},
    {"stage_id": "s8", "farming_method": "organic", "fertilizer_name": "Farmyard Manure", "rate": 300, "instructions": "Incorporate well-decomposed FYM into beds before planting."},
    {"stage_id": "s9", "farming_method": "conventional", "fertilizer_name": "Urea (46-0-0)", "rate": 25, "instructions": "Split application at 30 and 50 DAT for vegetative growth."},
    {"stage_id": "s9", "farming_method": "organic", "fertilizer_name": "Neem Cake", "rate": 40, "instructions": "Apply around root zone. Acts as fertilizer and pest deterrent."},
    {"stage_id": "s10", "farming_method": "conventional", "fertilizer_name": "Calcium Nitrate", "rate": 20, "instructions": "Apply during flowering to improve fruit quality."},
    {"stage_id": "s10", "farming_method": "organic", "fertilizer_name": "Seaweed Extract", "rate": 10, "instructions": "Foliar spray at 5ml/L during flower initiation."},
    {"stage_id": "s11", "farming_method": "conventional", "fertilizer_name": "MOP (Muriate of Potash)", "rate": 35, "instructions": "Apply during fruit development for better colour and size."},
    {"stage_id": "s11", "farming_method": "organic", "fertilizer_name": "Compost Tea", "rate": 50, "instructions": "Drench soil weekly with aerated compost tea."},
    {"stage_id": "s9", "farming_method": "conventional", "fertilizer_name": "DAP 18-46-0", "rate": 20, "instructions": "2nd split as top-dress at 45 DAT."},
    {"stage_id": "s10", "farming_method": "organic", "fertilizer_name": "Bone Meal", "rate": 25, "instructions": "Apply for phosphorus supply during flowering."},

    # ── Rice ────────────────────────────────
    {"stage_id": "s14", "farming_method": "conventional", "fertilizer_name": "TSP (Triple Super Phosphate)", "rate": 50, "instructions": "Apply entire P dose as basal at transplanting."},
    {"stage_id": "s14", "farming_method": "organic", "fertilizer_name": "Rock Phosphate", "rate": 60, "instructions": "Apply at transplanting. Slow-release phosphorus source."},
    {"stage_id": "s15", "farming_method": "conventional", "fertilizer_name": "Urea (46-0-0)", "rate": 50, "instructions": "1st split at active tillering. Drain water before applying."},
    {"stage_id": "s15", "farming_method": "organic", "fertilizer_name": "Azolla Incorporation", "rate": 100, "instructions": "Incorporate dried azolla into paddy field as green manure."},
    {"stage_id": "s15", "farming_method": "conventional", "fertilizer_name": "MOP (Muriate of Potash)", "rate": 30, "instructions": "Apply 50% of K as basal at tillering."},
    {"stage_id": "s15", "farming_method": "organic", "fertilizer_name": "Farmyard Manure", "rate": 500, "instructions": "Apply well-decomposed FYM at 5 tonnes/acre."},
    {"stage_id": "s16", "farming_method": "conventional", "fertilizer_name": "Urea (46-0-0)", "rate": 40, "instructions": "2nd split at panicle initiation. Critical N application."},
    {"stage_id": "s16", "farming_method": "organic", "fertilizer_name": "Vermicompost", "rate": 150, "instructions": "Top-dress at booting stage for grain quality."},
    {"stage_id": "s17", "farming_method": "conventional", "fertilizer_name": "Potassium Sulphate", "rate": 25, "instructions": "Final K dose during grain filling."},
    {"stage_id": "s17", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 50, "instructions": "Broadcast in field for potassium during grain filling."},

    # ── Brinjal ─────────────────────────────
    {"stage_id": "s20", "farming_method": "conventional", "fertilizer_name": "NPK 10-26-26", "rate": 50, "instructions": "Basal dose at transplanting."},
    {"stage_id": "s20", "farming_method": "organic", "fertilizer_name": "Vermicompost", "rate": 250, "instructions": "Mix into planting pits before transplanting."},
    {"stage_id": "s21", "farming_method": "conventional", "fertilizer_name": "Urea (46-0-0)", "rate": 35, "instructions": "1st top-dressing at 30 DAT. Band apply."},
    {"stage_id": "s21", "farming_method": "organic", "fertilizer_name": "Blood Meal", "rate": 20, "instructions": "Side-dress for nitrogen boost during vegetative phase."},
    {"stage_id": "s22", "farming_method": "conventional", "fertilizer_name": "Calcium Ammonium Nitrate", "rate": 25, "instructions": "Top-dress during flowering for fruit set."},
    {"stage_id": "s22", "farming_method": "organic", "fertilizer_name": "Bone Meal", "rate": 30, "instructions": "Apply for phosphorus and calcium during flowering."},
    {"stage_id": "s23", "farming_method": "conventional", "fertilizer_name": "MOP (Muriate of Potash)", "rate": 40, "instructions": "Apply during fruiting for better fruit quality."},
    {"stage_id": "s23", "farming_method": "organic", "fertilizer_name": "Compost Tea", "rate": 40, "instructions": "Weekly drench during fruiting phase."},
    {"stage_id": "s21", "farming_method": "conventional", "fertilizer_name": "DAP 18-46-0", "rate": 20, "instructions": "2nd phosphorus dose during active vegetative growth."},
    {"stage_id": "s22", "farming_method": "organic", "fertilizer_name": "Neem Cake", "rate": 35, "instructions": "Apply around base. Dual role: fertilizer + pest control."},

    # ── Beans ───────────────────────────────
    {"stage_id": "s26", "farming_method": "conventional", "fertilizer_name": "NPK 15-15-15", "rate": 30, "instructions": "Light basal dose. Beans fix their own nitrogen."},
    {"stage_id": "s26", "farming_method": "organic", "fertilizer_name": "Compost", "rate": 150, "instructions": "Apply well-decomposed compost at planting."},
    {"stage_id": "s27", "farming_method": "conventional", "fertilizer_name": "TSP (Triple Super Phosphate)", "rate": 25, "instructions": "Phosphorus boost for root development."},
    {"stage_id": "s27", "farming_method": "organic", "fertilizer_name": "Rock Phosphate", "rate": 30, "instructions": "Apply for slow-release phosphorus."},
    {"stage_id": "s28", "farming_method": "conventional", "fertilizer_name": "MOP (Muriate of Potash)", "rate": 20, "instructions": "Apply at flowering for pod formation."},
    {"stage_id": "s28", "farming_method": "organic", "fertilizer_name": "Kelp Meal", "rate": 15, "instructions": "Broadcast for potassium during flowering."},
    {"stage_id": "s29", "farming_method": "conventional", "fertilizer_name": "Potassium Sulphate", "rate": 15, "instructions": "Foliar spray during pod filling."},
    {"stage_id": "s29", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 25, "instructions": "Light broadcast for potassium during pod filling."},
    {"stage_id": "s27", "farming_method": "conventional", "fertilizer_name": "Borax", "rate": 2, "instructions": "Foliar spray (0.2%) for boron deficiency prevention."},
    {"stage_id": "s28", "farming_method": "organic", "fertilizer_name": "Seaweed Extract", "rate": 8, "instructions": "Foliar spray at 3ml/L during flowering."},

    # ── Onion (p6) ──────────────────────────
    {"stage_id": "s31", "farming_method": "conventional", "fertilizer_name": "Starter NPK 15-15-15", "rate": 40, "instructions": "Apply as basal dressing during bed preparation."},
    {"stage_id": "s31", "farming_method": "organic", "fertilizer_name": "Compost", "rate": 200, "instructions": "Mix into nursery bed before sowing."},
    {"stage_id": "s32", "farming_method": "conventional", "fertilizer_name": "Ammonium Sulphate", "rate": 30, "instructions": "Apply at transplanting to boost establishment."},
    {"stage_id": "s32", "farming_method": "organic", "fertilizer_name": "Vermicompost", "rate": 150, "instructions": "Work into planting rows during transplanting."},
    {"stage_id": "s33", "farming_method": "conventional", "fertilizer_name": "DAP (Diammonium Phosphate)", "rate": 35, "instructions": "Side-dress at 30 DAT during rapid leaf growth."},
    {"stage_id": "s33", "farming_method": "organic", "fertilizer_name": "Neem Cake", "rate": 50, "instructions": "Apply around roots; helps deter pests."},
    {"stage_id": "s34", "farming_method": "conventional", "fertilizer_name": "Potassium Nitrate", "rate": 25, "instructions": "Apply at bulb initiation to promote size."},
    {"stage_id": "s34", "farming_method": "organic", "fertilizer_name": "Kelp Meal", "rate": 20, "instructions": "Broadcast lightly around bulb base."},
    {"stage_id": "s35", "farming_method": "conventional", "fertilizer_name": "Calcium Nitrate", "rate": 30, "instructions": "Apply during bulb development for shelf life."},
    {"stage_id": "s35", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 40, "instructions": "Apply around plants for organic potassium."},
    {"stage_id": "s36", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during harvesting and curing."},
    {"stage_id": "s36", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during harvesting and curing."},

    # ── Potato (p7) ──────────────────────────
    {"stage_id": "s37", "farming_method": "conventional", "fertilizer_name": "Starter NPK 10-26-26", "rate": 50, "instructions": "Incorporate in furrows at planting."},
    {"stage_id": "s37", "farming_method": "organic", "fertilizer_name": "Well-rotted Manure", "rate": 300, "instructions": "Spread and mix into soil during land preparation."},
    {"stage_id": "s38", "farming_method": "conventional", "fertilizer_name": "Ammonium Nitrate", "rate": 30, "instructions": "Apply during vegetative growth phase."},
    {"stage_id": "s38", "farming_method": "organic", "fertilizer_name": "Blood Meal", "rate": 20, "instructions": "Side-dress to supply organic nitrogen."},
    {"stage_id": "s39", "farming_method": "conventional", "fertilizer_name": "DAP (Diammonium Phosphate)", "rate": 25, "instructions": "Apply at stolon initiation to support rooting."},
    {"stage_id": "s39", "farming_method": "organic", "fertilizer_name": "Bone Meal", "rate": 25, "instructions": "Apply for organic phosphorus at stolon phase."},
    {"stage_id": "s40", "farming_method": "conventional", "fertilizer_name": "Calcium Nitrate", "rate": 30, "instructions": "Apply during tuber initiation to prevent defects."},
    {"stage_id": "s40", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 30, "instructions": "Lightly dust root zone to add potassium."},
    {"stage_id": "s41", "farming_method": "conventional", "fertilizer_name": "Potassium Nitrate", "rate": 35, "instructions": "Apply during tuber bulking for size growth."},
    {"stage_id": "s41", "farming_method": "organic", "fertilizer_name": "Seaweed Drench", "rate": 15, "instructions": "Apply liquid seaweed to boost root uptake."},
    {"stage_id": "s42", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications before harvesting."},
    {"stage_id": "s42", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications before harvesting."},

    # ── Cassava (p8) ──────────────────────────
    {"stage_id": "s43", "farming_method": "conventional", "fertilizer_name": "Basal NPK 15-15-15", "rate": 60, "instructions": "Apply in ridges before planting cuttings."},
    {"stage_id": "s43", "farming_method": "organic", "fertilizer_name": "Vermicompost", "rate": 250, "instructions": "Apply in planting pits to enrich soil structure."},
    {"stage_id": "s44", "farming_method": "conventional", "fertilizer_name": "Ammonium Nitrate", "rate": 40, "instructions": "Apply at 1 month to boost canopy development."},
    {"stage_id": "s44", "farming_method": "organic", "fertilizer_name": "Fish Emulsion", "rate": 20, "instructions": "Dilute and drench for nitrogen supply."},
    {"stage_id": "s45", "farming_method": "conventional", "fertilizer_name": "Potassium Chloride", "rate": 30, "instructions": "Apply at 3 months for root initiation support."},
    {"stage_id": "s45", "farming_method": "organic", "fertilizer_name": "Kelp Meal", "rate": 20, "instructions": "Apply to supply potassium for tuber start."},
    {"stage_id": "s46", "farming_method": "conventional", "fertilizer_name": "Potassium Sulphate", "rate": 30, "instructions": "Apply at 5 months for bulking phase."},
    {"stage_id": "s46", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 40, "instructions": "Broadcast to provide potassium for starch storage."},
    {"stage_id": "s47", "farming_method": "conventional", "fertilizer_name": "Potassium Nitrate", "rate": 25, "instructions": "Apply at 7 months to complete bulking."},
    {"stage_id": "s47", "farming_method": "organic", "fertilizer_name": "Compost Tea", "rate": 50, "instructions": "Weekly soil drench to maintain micro-nutrients."},
    {"stage_id": "s48", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during harvesting."},
    {"stage_id": "s48", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during harvesting."},

    # ── Finger Millet (p9) ────────────────────
    {"stage_id": "s49", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "No fertilizer during germination."},
    {"stage_id": "s49", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "No fertilizer during germination."},
    {"stage_id": "s50", "farming_method": "conventional", "fertilizer_name": "Basal NPK 12-12-12", "rate": 30, "instructions": "Incorporate during final land prep."},
    {"stage_id": "s50", "farming_method": "organic", "fertilizer_name": "Compost", "rate": 150, "instructions": "Mix into soil before seed sowing/transplanting."},
    {"stage_id": "s51", "farming_method": "conventional", "fertilizer_name": "Ammonium Sulphate", "rate": 20, "instructions": "Apply during tillering to boost shoots."},
    {"stage_id": "s51", "farming_method": "organic", "fertilizer_name": "Neem Cake", "rate": 30, "instructions": "Broadcast at tillering to deter stem borers."},
    {"stage_id": "s52", "farming_method": "conventional", "fertilizer_name": "DAP (Diammonium Phosphate)", "rate": 15, "instructions": "Apply at booting stage."},
    {"stage_id": "s52", "farming_method": "organic", "fertilizer_name": "Bone Meal", "rate": 20, "instructions": "Apply for phosphorus at flowering start."},
    {"stage_id": "s53", "farming_method": "conventional", "fertilizer_name": "Potassium Nitrate", "rate": 15, "instructions": "Apply during grain filling for seed yield."},
    {"stage_id": "s53", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 25, "instructions": "Broadcast lightly across field for potassium."},
    {"stage_id": "s54", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications at harvest."},
    {"stage_id": "s54", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications at harvest."},

    # ── Coconut (p10) ──────────────────────────
    {"stage_id": "s55", "farming_method": "conventional", "fertilizer_name": "Starter NPK 12-12-17", "rate": 50, "instructions": "Mix into pit before seedling planting."},
    {"stage_id": "s55", "farming_method": "organic", "fertilizer_name": "Farmyard Manure", "rate": 300, "instructions": "Mix well-decomposed manure into planting pit."},
    {"stage_id": "s56", "farming_method": "conventional", "fertilizer_name": "Ammonium Sulphate", "rate": 20, "instructions": "Apply 6 months DAT to support leaf crown."},
    {"stage_id": "s56", "farming_method": "organic", "fertilizer_name": "Neem Cake", "rate": 40, "instructions": "Apply around roots to deter root-eating pests."},
    {"stage_id": "s57", "farming_method": "conventional", "fertilizer_name": "Potassium Chloride", "rate": 30, "instructions": "Apply to support young trunk formation."},
    {"stage_id": "s57", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 50, "instructions": "Incorporate in basin around young palm."},
    {"stage_id": "s58", "farming_method": "conventional", "fertilizer_name": "Dolomite", "rate": 25, "instructions": "Apply to raise soil magnesium and calcium."},
    {"stage_id": "s58", "farming_method": "organic", "fertilizer_name": "Bone Meal", "rate": 30, "instructions": "Apply around root zone basin."},
    {"stage_id": "s59", "farming_method": "conventional", "fertilizer_name": "Ammonium Sulphate", "rate": 25, "instructions": "Apply as split dose before monsoon season."},
    {"stage_id": "s59", "farming_method": "organic", "fertilizer_name": "Compost Tea", "rate": 40, "instructions": "Drench root zone area around basin."},
    {"stage_id": "s60", "farming_method": "conventional", "fertilizer_name": "Potassium Nitrate", "rate": 45, "instructions": "Apply to prepare young palm for bearing phase."},
    {"stage_id": "s60", "farming_method": "organic", "fertilizer_name": "Fish Emulsion", "rate": 20, "instructions": "Drench root basin area to feed soil biology."},

    # ── Green Gram (p11) ──────────────────────
    {"stage_id": "s61", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "No fertilizer during germination."},
    {"stage_id": "s61", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "No fertilizer during germination."},
    {"stage_id": "s62", "farming_method": "conventional", "fertilizer_name": "Basal NPK 10-26-26", "rate": 20, "instructions": "Apply basal dressing near roots at seedling stage."},
    {"stage_id": "s62", "farming_method": "organic", "fertilizer_name": "Compost", "rate": 100, "instructions": "Apply organic compost during seedling establishment."},
    {"stage_id": "s63", "farming_method": "conventional", "fertilizer_name": "Single Superphosphate", "rate": 25, "instructions": "Apply at 15 DAS to support leaf growth."},
    {"stage_id": "s63", "farming_method": "organic", "fertilizer_name": "Gypsum", "rate": 30, "instructions": "Incorporate gypsum to supply sulfur and calcium."},
    {"stage_id": "s64", "farming_method": "conventional", "fertilizer_name": "Ammonium Nitrate foliar spray", "rate": 5, "instructions": "Spray 1% solution at flower initiation."},
    {"stage_id": "s64", "farming_method": "organic", "fertilizer_name": "Seaweed Extract", "rate": 5, "instructions": "Foliar spray to stimulate flowering."},
    {"stage_id": "s65", "farming_method": "conventional", "fertilizer_name": "Potassium Sulphate", "rate": 15, "instructions": "Apply during pod development."},
    {"stage_id": "s65", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 20, "instructions": "Broadcast lightly around pod-bearing stems."},
    {"stage_id": "s66", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during harvesting."},
    {"stage_id": "s66", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during harvesting."},

    # ── Okra (p12) ───────────────────────────
    {"stage_id": "s67", "farming_method": "conventional", "fertilizer_name": "Starter NPK 15-15-15", "rate": 30, "instructions": "Basal dressing in sowing holes."},
    {"stage_id": "s67", "farming_method": "organic", "fertilizer_name": "Vermicompost", "rate": 150, "instructions": "Mix into soil during sowing."},
    {"stage_id": "s68", "farming_method": "conventional", "fertilizer_name": "Ammonium Nitrate", "rate": 20, "instructions": "Apply 14 DAS after seedling emergence."},
    {"stage_id": "s68", "farming_method": "organic", "fertilizer_name": "Neem Cake", "rate": 30, "instructions": "Side-dress around root zone to protect seedling."},
    {"stage_id": "s69", "farming_method": "conventional", "fertilizer_name": "Ammonium Sulphate", "rate": 25, "instructions": "Apply at 30 DAS during active vegetative stage."},
    {"stage_id": "s69", "farming_method": "organic", "fertilizer_name": "Blood Meal", "rate": 15, "instructions": "Broadcast lightly for vegetative nitrogen boost."},
    {"stage_id": "s70", "farming_method": "conventional", "fertilizer_name": "Calcium Nitrate", "rate": 20, "instructions": "Apply at flower initiation to help fruit set."},
    {"stage_id": "s70", "farming_method": "organic", "fertilizer_name": "Bone Meal", "rate": 20, "instructions": "Apply for organic phosphorus during flowering."},
    {"stage_id": "s71", "farming_method": "conventional", "fertilizer_name": "Potassium Chloride", "rate": 25, "instructions": "Apply during pod formation for size quality."},
    {"stage_id": "s71", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 30, "instructions": "Dust soil basin for potassium enrichment."},
    {"stage_id": "s72", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during harvest flushes."},
    {"stage_id": "s72", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during harvest flushes."},

    # ── Cowpea (p13) ─────────────────────────
    {"stage_id": "s73", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "No fertilizer during germination."},
    {"stage_id": "s73", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "No fertilizer during germination."},
    {"stage_id": "s74", "farming_method": "conventional", "fertilizer_name": "Basal NPK 10-26-26", "rate": 15, "instructions": "Apply basal dressing in planting furrow."},
    {"stage_id": "s74", "farming_method": "organic", "fertilizer_name": "Farmyard Manure", "rate": 120, "instructions": "Mix decomposed FYM in soil during sowing."},
    {"stage_id": "s75", "farming_method": "conventional", "fertilizer_name": "Single Superphosphate", "rate": 25, "instructions": "Apply at 20 DAS for root nodules support."},
    {"stage_id": "s75", "farming_method": "organic", "fertilizer_name": "Compost", "rate": 150, "instructions": "Apply organic compost to soil surface."},
    {"stage_id": "s76", "farming_method": "conventional", "fertilizer_name": "Potassium Chloride", "rate": 15, "instructions": "Apply at flowering to support pod set."},
    {"stage_id": "s76", "farming_method": "organic", "fertilizer_name": "Kelp Meal", "rate": 10, "instructions": "Broadcast around plants during flower initiation."},
    {"stage_id": "s77", "farming_method": "conventional", "fertilizer_name": "Zinc Sulphate", "rate": 5, "instructions": "Apply during pod development."},
    {"stage_id": "s77", "farming_method": "organic", "fertilizer_name": "Seaweed Extract", "rate": 5, "instructions": "Foliar spray to improve pod filling."},
    {"stage_id": "s78", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during harvest."},
    {"stage_id": "s78", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during harvest."},

    # ── Bitter Gourd (p14) ───────────────────
    {"stage_id": "s79", "farming_method": "conventional", "fertilizer_name": "Basal NPK 15-15-15", "rate": 30, "instructions": "Apply to pits before sowing seeds."},
    {"stage_id": "s79", "farming_method": "organic", "fertilizer_name": "Farmyard Manure", "rate": 200, "instructions": "Mix into pits before planting."},
    {"stage_id": "s80", "farming_method": "conventional", "fertilizer_name": "Ammonium Nitrate", "rate": 25, "instructions": "Side-dress at 15 DAT during vine growth."},
    {"stage_id": "s80", "farming_method": "organic", "fertilizer_name": "Neem Cake", "rate": 45, "instructions": "Mix around stem base to feed and protect vine."},
    {"stage_id": "s81", "farming_method": "conventional", "fertilizer_name": "DAP (Diammonium Phosphate)", "rate": 20, "instructions": "Apply at 45 DAT during flowering and trellising."},
    {"stage_id": "s81", "farming_method": "organic", "fertilizer_name": "Bone Meal", "rate": 25, "instructions": "Incorporate for phosphorus at flowering stage."},
    {"stage_id": "s82", "farming_method": "conventional", "fertilizer_name": "Calcium Nitrate", "rate": 15, "instructions": "Apply during early fruit set."},
    {"stage_id": "s82", "farming_method": "organic", "fertilizer_name": "Compost Tea", "rate": 40, "instructions": "Weekly soil drench around vine roots."},
    {"stage_id": "s83", "farming_method": "conventional", "fertilizer_name": "Potassium Chloride", "rate": 30, "instructions": "Apply during fruit development for size growth."},
    {"stage_id": "s83", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 35, "instructions": "Dust circular basin area for potassium."},
    {"stage_id": "s84", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during harvesting."},
    {"stage_id": "s84", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during harvesting."},

    # ── Sweet Potato (p15) ───────────────────
    {"stage_id": "s85", "farming_method": "conventional", "fertilizer_name": "Starter NPK 10-26-26", "rate": 35, "instructions": "Incorporate in ridges before planting vine cuttings."},
    {"stage_id": "s85", "farming_method": "organic", "fertilizer_name": "Well-rotted Manure", "rate": 200, "instructions": "Mix into soil bed during ridge preparation."},
    {"stage_id": "s86", "farming_method": "conventional", "fertilizer_name": "Ammonium Sulphate", "rate": 25, "instructions": "Apply at 2 weeks DAT to boost vine establishment."},
    {"stage_id": "s86", "farming_method": "organic", "fertilizer_name": "Vermicompost", "rate": 150, "instructions": "Apply in furrows along the planting rows."},
    {"stage_id": "s87", "farming_method": "conventional", "fertilizer_name": "Single Superphosphate", "rate": 30, "instructions": "Apply at 5 weeks DAT to support tuber initiation."},
    {"stage_id": "s87", "farming_method": "organic", "fertilizer_name": "Bone Meal", "rate": 30, "instructions": "Work into soil to supply phosphorus during initiation."},
    {"stage_id": "s88", "farming_method": "conventional", "fertilizer_name": "Potassium Chloride", "rate": 35, "instructions": "Apply at 7 weeks DAT during tuber development."},
    {"stage_id": "s88", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 40, "instructions": "Broadcast on ridges for potassium uptake."},
    {"stage_id": "s89", "farming_method": "conventional", "fertilizer_name": "Potassium Sulphate", "rate": 30, "instructions": "Apply at 9 weeks DAT during main bulking stage."},
    {"stage_id": "s89", "farming_method": "organic", "fertilizer_name": "Kelp Meal", "rate": 25, "instructions": "Incorporate to supply potassium for starch bulking."},
    {"stage_id": "s90", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications 2 weeks before harvest."},
    {"stage_id": "s90", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications 2 weeks before harvest."},

    # ── Peanut (p16) ─────────────────────────
    {"stage_id": "s91", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "No fertilizer during germination."},
    {"stage_id": "s91", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "No fertilizer during germination."},
    {"stage_id": "s92", "farming_method": "conventional", "fertilizer_name": "Ammonium Phosphate", "rate": 15, "instructions": "Apply to support seedling roots growth."},
    {"stage_id": "s92", "farming_method": "organic", "fertilizer_name": "Compost", "rate": 100, "instructions": "Mix organic compost in the seedling rows."},
    {"stage_id": "s93", "farming_method": "conventional", "fertilizer_name": "Single Superphosphate", "rate": 30, "instructions": "Apply at early flowering to support flower buds."},
    {"stage_id": "s93", "farming_method": "organic", "fertilizer_name": "Gypsum", "rate": 50, "instructions": "Apply gypsum during early flowering to supply sulfur and calcium."},
    {"stage_id": "s94", "farming_method": "conventional", "fertilizer_name": "Gypsum", "rate": 100, "instructions": "Pegging phase requires high soil calcium."},
    {"stage_id": "s94", "farming_method": "organic", "fertilizer_name": "Farmyard Manure", "rate": 150, "instructions": "Apply composted FYM to loosen soil for pegs entry."},
    {"stage_id": "s95", "farming_method": "conventional", "fertilizer_name": "Potassium Sulphate", "rate": 20, "instructions": "Apply during pod filling stage."},
    {"stage_id": "s95", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 25, "instructions": "Broadcast wood ash lightly to enrich potassium."},
    {"stage_id": "s96", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications for harvesting."},
    {"stage_id": "s96", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications for harvesting."},

    # ── Black Gram (p17) ──────────────────────
    {"stage_id": "s97", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "No fertilizer during germination."},
    {"stage_id": "s97", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "No fertilizer during germination."},
    {"stage_id": "s98", "farming_method": "conventional", "fertilizer_name": "Basal NPK 10-26-26", "rate": 15, "instructions": "Apply basal dressing near root zone."},
    {"stage_id": "s98", "farming_method": "organic", "fertilizer_name": "Compost", "rate": 120, "instructions": "Mix into planting rows."},
    {"stage_id": "s99", "farming_method": "conventional", "fertilizer_name": "Ammonium Nitrate", "rate": 10, "instructions": "Apply side-dressing at active vegetative growth."},
    {"stage_id": "s99", "farming_method": "organic", "fertilizer_name": "Neem Cake", "rate": 25, "instructions": "Apply to support root health and soil biology."},
    {"stage_id": "s100", "farming_method": "conventional", "fertilizer_name": "Single Superphosphate", "rate": 25, "instructions": "Apply during early flowering."},
    {"stage_id": "s100", "farming_method": "organic", "fertilizer_name": "Bone Meal", "rate": 20, "instructions": "Incorporate bone meal for organic phosphorus."},
    {"stage_id": "s101", "farming_method": "conventional", "fertilizer_name": "Potassium Sulphate", "rate": 15, "instructions": "Apply at early pod stage."},
    {"stage_id": "s101", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 20, "instructions": "Broadcast lightly around stems."},
    {"stage_id": "s102", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications."},
    {"stage_id": "s102", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications."},

    # ── Soybean (p18) ─────────────────────────
    {"stage_id": "s103", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "No fertilizer during germination."},
    {"stage_id": "s103", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "No fertilizer during germination."},
    {"stage_id": "s104", "farming_method": "conventional", "fertilizer_name": "Basal NPK 12-32-16", "rate": 20, "instructions": "Apply basal dressing in sowing holes."},
    {"stage_id": "s104", "farming_method": "organic", "fertilizer_name": "Compost", "rate": 150, "instructions": "Mix into soil during seedling stage."},
    {"stage_id": "s105", "farming_method": "conventional", "fertilizer_name": "Ammonium Nitrate", "rate": 15, "instructions": "Apply at active vegetative growth."},
    {"stage_id": "s105", "farming_method": "organic", "fertilizer_name": "Neem Cake", "rate": 30, "instructions": "Apply to improve soil health."},
    {"stage_id": "s106", "farming_method": "conventional", "fertilizer_name": "Single Superphosphate", "rate": 35, "instructions": "Apply during flowering to support pod set."},
    {"stage_id": "s106", "farming_method": "organic", "fertilizer_name": "Bone Meal", "rate": 25, "instructions": "Apply bone meal around stem base."},
    {"stage_id": "s107", "farming_method": "conventional", "fertilizer_name": "Potassium Sulphate", "rate": 25, "instructions": "Apply during pod filling stage."},
    {"stage_id": "s107", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 30, "instructions": "Broadcast wood ash to supply potassium."},
    {"stage_id": "s108", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications."},
    {"stage_id": "s108", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications."},

    # ── Maize (p19) ───────────────────────────
    {"stage_id": "s109", "farming_method": "conventional", "fertilizer_name": "Starter NPK 15-15-15", "rate": 30, "instructions": "Basal application during sowing."},
    {"stage_id": "s109", "farming_method": "organic", "fertilizer_name": "Compost", "rate": 150, "instructions": "Mix into soil beds during sowing."},
    {"stage_id": "s110", "farming_method": "conventional", "fertilizer_name": "Urea", "rate": 50, "instructions": "Side-dress at 25 DAS to boost vegetative leaf growth."},
    {"stage_id": "s110", "farming_method": "organic", "fertilizer_name": "Poultry Manure", "rate": 120, "instructions": "Broadcast dry poultry manure along crop rows."},
    {"stage_id": "s111", "farming_method": "conventional", "fertilizer_name": "Ammonium Nitrate", "rate": 30, "instructions": "Apply at early tasseling stage."},
    {"stage_id": "s111", "farming_method": "organic", "fertilizer_name": "Vermicompost", "rate": 100, "instructions": "Apply vermicompost along maize root zones."},
    {"stage_id": "s112", "farming_method": "conventional", "fertilizer_name": "Calcium Nitrate", "rate": 25, "instructions": "Apply at silking to improve grain set."},
    {"stage_id": "s112", "farming_method": "organic", "fertilizer_name": "Fish Emulsion", "rate": 15, "instructions": "Foliar drench to feed crop leaves during silking."},
    {"stage_id": "s113", "farming_method": "conventional", "fertilizer_name": "Potassium Chloride", "rate": 30, "instructions": "Apply at dough stage for starch grain filling."},
    {"stage_id": "s113", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 35, "instructions": "Incorporate wood ash around root zones."},
    {"stage_id": "s114", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during mature drying."},
    {"stage_id": "s114", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during mature drying."},

    # ── Pearl Millet (p20) ────────────────────
    {"stage_id": "s115", "farming_method": "conventional", "fertilizer_name": "Starter NPK 15-15-15", "rate": 20, "instructions": "Apply basal dressing in sowing rows."},
    {"stage_id": "s115", "farming_method": "organic", "fertilizer_name": "Compost", "rate": 100, "instructions": "Mix into soil during bed sowing."},
    {"stage_id": "s116", "farming_method": "conventional", "fertilizer_name": "Urea", "rate": 25, "instructions": "Apply side-dressing at tillering stage."},
    {"stage_id": "s116", "farming_method": "organic", "fertilizer_name": "Neem Cake", "rate": 30, "instructions": "Apply neem cake to improve soil health."},
    {"stage_id": "s117", "farming_method": "conventional", "fertilizer_name": "Ammonium Nitrate", "rate": 20, "instructions": "Apply at stem elongation phase."},
    {"stage_id": "s117", "farming_method": "organic", "fertilizer_name": "Farmyard Manure", "rate": 100, "instructions": "Broadcast composted FYM along lines."},
    {"stage_id": "s118", "farming_method": "conventional", "fertilizer_name": "Single Superphosphate", "rate": 15, "instructions": "Apply at heading to support grain set."},
    {"stage_id": "s118", "farming_method": "organic", "fertilizer_name": "Bone Meal", "rate": 15, "instructions": "Apply bone meal around stem base."},
    {"stage_id": "s119", "farming_method": "conventional", "fertilizer_name": "Potassium Chloride", "rate": 15, "instructions": "Apply during grain bulking."},
    {"stage_id": "s119", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 20, "instructions": "Broadcast wood ash lightly to enrich potassium."},
    {"stage_id": "s120", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications."},
    {"stage_id": "s120", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications."},

    # ── Sorghum (p21) ─────────────────────────
    {"stage_id": "s121", "farming_method": "conventional", "fertilizer_name": "Starter NPK 15-15-15", "rate": 25, "instructions": "Apply basal dressing in furrows."},
    {"stage_id": "s121", "farming_method": "organic", "fertilizer_name": "Compost", "rate": 120, "instructions": "Mix into sowing furrows."},
    {"stage_id": "s122", "farming_method": "conventional", "fertilizer_name": "Urea", "rate": 35, "instructions": "Apply side-dressing at active tillering."},
    {"stage_id": "s122", "farming_method": "organic", "fertilizer_name": "Poultry Manure", "rate": 80, "instructions": "Broadcast dry poultry manure between rows."},
    {"stage_id": "s123", "farming_method": "conventional", "fertilizer_name": "DAP (Diammonium Phosphate)", "rate": 20, "instructions": "Apply at booting stage for head development."},
    {"stage_id": "s123", "farming_method": "organic", "fertilizer_name": "Neem Cake", "rate": 35, "instructions": "Side-dress around root zone."},
    {"stage_id": "s124", "farming_method": "conventional", "fertilizer_name": "Calcium Nitrate", "rate": 20, "instructions": "Apply at flowering to support grain set."},
    {"stage_id": "s124", "farming_method": "organic", "fertilizer_name": "Bone Meal", "rate": 20, "instructions": "Apply bone meal along roots."},
    {"stage_id": "s125", "farming_method": "conventional", "fertilizer_name": "Potassium Chloride", "rate": 25, "instructions": "Apply during grain bulking."},
    {"stage_id": "s125", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 30, "instructions": "Broadcast wood ash to provide potassium."},
    {"stage_id": "s126", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during drying."},
    {"stage_id": "s126", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during drying."},

    # ── Foxtail Millet (p22) ──────────────────
    {"stage_id": "s127", "farming_method": "conventional", "fertilizer_name": "Starter NPK 15-15-15", "rate": 15, "instructions": "Apply basal dressing during sowing."},
    {"stage_id": "s127", "farming_method": "organic", "fertilizer_name": "Compost", "rate": 80, "instructions": "Mix into soil bed during sowing."},
    {"stage_id": "s128", "farming_method": "conventional", "fertilizer_name": "Urea", "rate": 20, "instructions": "Apply side-dressing at tillering stage."},
    {"stage_id": "s128", "farming_method": "organic", "fertilizer_name": "Vermicompost", "rate": 80, "instructions": "Apply vermicompost along millet rows."},
    {"stage_id": "s129", "farming_method": "conventional", "fertilizer_name": "Ammonium Nitrate", "rate": 15, "instructions": "Apply at stem elongation."},
    {"stage_id": "s129", "farming_method": "organic", "fertilizer_name": "Farmyard Manure", "rate": 80, "instructions": "Broadcast composted FYM along lines."},
    {"stage_id": "s130", "farming_method": "conventional", "fertilizer_name": "Single Superphosphate", "rate": 10, "instructions": "Apply at panicle emergence."},
    {"stage_id": "s130", "farming_method": "organic", "fertilizer_name": "Bone Meal", "rate": 12, "instructions": "Apply bone meal to root zones."},
    {"stage_id": "s131", "farming_method": "conventional", "fertilizer_name": "Potassium Chloride", "rate": 12, "instructions": "Apply during grain filling."},
    {"stage_id": "s131", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 15, "instructions": "Broadcast wood ash lightly."},
    {"stage_id": "s132", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications."},
    {"stage_id": "s132", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications."},

    # ── Gotukola (p23) ────────────────────────
    {"stage_id": "s133", "farming_method": "conventional", "fertilizer_name": "Starter NPK 15-15-15", "rate": 15, "instructions": "Basal application during plant rooting."},
    {"stage_id": "s133", "farming_method": "organic", "fertilizer_name": "Vermicompost", "rate": 120, "instructions": "Mix into soil beds during planting."},
    {"stage_id": "s134", "farming_method": "conventional", "fertilizer_name": "Ammonium Sulphate", "rate": 20, "instructions": "Apply at runner development to support vine growth."},
    {"stage_id": "s134", "farming_method": "organic", "fertilizer_name": "Compost", "rate": 150, "instructions": "Apply compost over planting beds."},
    {"stage_id": "s135", "farming_method": "conventional", "fertilizer_name": "Urea", "rate": 25, "instructions": "Apply foliar dressing for leaf extension."},
    {"stage_id": "s135", "farming_method": "organic", "fertilizer_name": "Blood Meal", "rate": 20, "instructions": "Apply blood meal for vegetative nitrogen boost."},
    {"stage_id": "s136", "farming_method": "conventional", "fertilizer_name": "Calcium Nitrate", "rate": 15, "instructions": "Apply to support leaf cell wall strength."},
    {"stage_id": "s136", "farming_method": "organic", "fertilizer_name": "Fish Emulsion", "rate": 15, "instructions": "Foliar spray to feed crop leaves."},
    {"stage_id": "s137", "farming_method": "conventional", "fertilizer_name": "Potassium Sulphate", "rate": 15, "instructions": "Apply before primary harvest."},
    {"stage_id": "s137", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 25, "instructions": "Broadcast wood ash over soil base."},
    {"stage_id": "s138", "farming_method": "conventional", "fertilizer_name": "Ammonium Nitrate", "rate": 10, "instructions": "Apply after first harvest to support secondary growth."},
    {"stage_id": "s138", "farming_method": "organic", "fertilizer_name": "Kelp Meal", "rate": 10, "instructions": "Apply kelp meal to stimulate regrowth."},

    # ── Spinach (p24) ─────────────────────────
    {"stage_id": "s139", "farming_method": "conventional", "fertilizer_name": "Starter NPK 15-15-15", "rate": 20, "instructions": "Apply basal dressing in sowing holes."},
    {"stage_id": "s139", "farming_method": "organic", "fertilizer_name": "Vermicompost", "rate": 100, "instructions": "Mix vermicompost into seedbeds."},
    {"stage_id": "s140", "farming_method": "conventional", "fertilizer_name": "Ammonium Nitrate", "rate": 15, "instructions": "Apply side-dressing at 10 DAS."},
    {"stage_id": "s140", "farming_method": "organic", "fertilizer_name": "Compost", "rate": 120, "instructions": "Apply compost along seedling rows."},
    {"stage_id": "s141", "farming_method": "conventional", "fertilizer_name": "Urea", "rate": 20, "instructions": "Apply foliar dressing for green leafy growth."},
    {"stage_id": "s141", "farming_method": "organic", "fertilizer_name": "Blood Meal", "rate": 15, "instructions": "Apply blood meal to stimulate nitrogen uptake."},
    {"stage_id": "s142", "farming_method": "conventional", "fertilizer_name": "Calcium Nitrate", "rate": 15, "instructions": "Apply to support leaf turgidity."},
    {"stage_id": "s142", "farming_method": "organic", "fertilizer_name": "Fish Emulsion", "rate": 12, "instructions": "Foliar spray to enrich leaf quality."},
    {"stage_id": "s143", "farming_method": "conventional", "fertilizer_name": "Potassium Sulphate", "rate": 12, "instructions": "Apply 1 week before harvesting."},
    {"stage_id": "s143", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 20, "instructions": "Broadcast wood ash lightly over bed."},
    {"stage_id": "s144", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during harvest."},
    {"stage_id": "s144", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during harvest."},

    # ── Beetroot (p25) ────────────────────────
    {"stage_id": "s145", "farming_method": "conventional", "fertilizer_name": "Starter NPK 15-15-15", "rate": 25, "instructions": "Apply basal dressing in planting beds."},
    {"stage_id": "s145", "farming_method": "organic", "fertilizer_name": "Compost", "rate": 150, "instructions": "Mix into soil during sowing."},
    {"stage_id": "s146", "farming_method": "conventional", "fertilizer_name": "Ammonium Nitrate", "rate": 20, "instructions": "Apply side-dressing at 14 DAS."},
    {"stage_id": "s146", "farming_method": "organic", "fertilizer_name": "Vermicompost", "rate": 100, "instructions": "Apply along seedling rows."},
    {"stage_id": "s147", "farming_method": "conventional", "fertilizer_name": "Urea", "rate": 20, "instructions": "Apply to support foliar canopy development."},
    {"stage_id": "s147", "farming_method": "organic", "fertilizer_name": "Fish Emulsion", "rate": 15, "instructions": "Foliar drench to support leaves growth."},
    {"stage_id": "s148", "farming_method": "conventional", "fertilizer_name": "Single Superphosphate", "rate": 25, "instructions": "Apply during root initiation stage."},
    {"stage_id": "s148", "farming_method": "organic", "fertilizer_name": "Bone Meal", "rate": 25, "instructions": "Apply bone meal to support root expansion."},
    {"stage_id": "s149", "farming_method": "conventional", "fertilizer_name": "Potassium Chloride", "rate": 35, "instructions": "Apply during root bulking phase."},
    {"stage_id": "s149", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 40, "instructions": "Incorporate wood ash around beet bulbs."},
    {"stage_id": "s150", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications before harvest."},
    {"stage_id": "s150", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications before harvest."},

    # ── Radish (p26) ──────────────────────────
    {"stage_id": "s151", "farming_method": "conventional", "fertilizer_name": "Starter NPK 15-15-15", "rate": 15, "instructions": "Apply basal dressing in sowing holes."},
    {"stage_id": "s151", "farming_method": "organic", "fertilizer_name": "Compost", "rate": 100, "instructions": "Mix into soil during sowing."},
    {"stage_id": "s152", "farming_method": "conventional", "fertilizer_name": "Ammonium Nitrate", "rate": 12, "instructions": "Apply side-dressing at 10 DAS."},
    {"stage_id": "s152", "farming_method": "organic", "fertilizer_name": "Vermicompost", "rate": 80, "instructions": "Apply along seedling rows."},
    {"stage_id": "s153", "farming_method": "conventional", "fertilizer_name": "Urea", "rate": 15, "instructions": "Apply foliar dressing for canopy growth."},
    {"stage_id": "s153", "farming_method": "organic", "fertilizer_name": "Blood Meal", "rate": 10, "instructions": "Apply blood meal to stimulate nitrogen uptake."},
    {"stage_id": "s154", "farming_method": "conventional", "fertilizer_name": "Single Superphosphate", "rate": 15, "instructions": "Apply during root swelling phase."},
    {"stage_id": "s154", "farming_method": "organic", "fertilizer_name": "Bone Meal", "rate": 15, "instructions": "Incorporate bone meal around root swells."},
    {"stage_id": "s155", "farming_method": "conventional", "fertilizer_name": "Potassium Chloride", "rate": 20, "instructions": "Apply during root maturation stage."},
    {"stage_id": "s155", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 25, "instructions": "Broadcast wood ash lightly over bed."},
    {"stage_id": "s156", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during harvest."},
    {"stage_id": "s156", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications during harvest."},

    # ── Yam (p27) ─────────────────────────────
    {"stage_id": "s157", "farming_method": "conventional", "fertilizer_name": "Starter NPK 12-32-16", "rate": 40, "instructions": "Apply basal dressing in planting pits."},
    {"stage_id": "s157", "farming_method": "organic", "fertilizer_name": "Well-rotted manure", "rate": 250, "instructions": "Mix into pits during planting."},
    {"stage_id": "s158", "farming_method": "conventional", "fertilizer_name": "Ammonium Sulphate", "rate": 30, "instructions": "Apply at active vine growth stage."},
    {"stage_id": "s158", "farming_method": "organic", "fertilizer_name": "Vermicompost", "rate": 200, "instructions": "Apply in furrows along planting rows."},
    {"stage_id": "s159", "farming_method": "conventional", "fertilizer_name": "Urea", "rate": 35, "instructions": "Apply at canopy development to support foliage."},
    {"stage_id": "s159", "farming_method": "organic", "fertilizer_name": "Neem Cake", "rate": 50, "instructions": "Incorporate around vine roots base."},
    {"stage_id": "s160", "farming_method": "conventional", "fertilizer_name": "DAP (Diammonium Phosphate)", "rate": 30, "instructions": "Apply during tuber initiation phase."},
    {"stage_id": "s160", "farming_method": "organic", "fertilizer_name": "Bone Meal", "rate": 35, "instructions": "Apply bone meal around root base."},
    {"stage_id": "s161", "farming_method": "conventional", "fertilizer_name": "Potassium Chloride", "rate": 50, "instructions": "Apply during tuber bulking stage."},
    {"stage_id": "s161", "farming_method": "organic", "fertilizer_name": "Wood Ash", "rate": 60, "instructions": "Incorporate wood ash around tuber basin area."},
    {"stage_id": "s162", "farming_method": "conventional", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications 2 weeks before harvest."},
    {"stage_id": "s162", "farming_method": "organic", "fertilizer_name": "No Application", "rate": 0, "instructions": "Cease all applications 2 weeks before harvest."},
]
