plants = [{'id': 'p1', 'name': 'Tomato'},
 {'id': 'p2', 'name': 'Chili'},
 {'id': 'p3', 'name': 'Rice'},
 {'id': 'p4', 'name': 'Brinjal'},
 {'id': 'p5', 'name': 'Beans'},
 {'id': 'p6', 'name': 'Onion'},
 {'id': 'p7', 'name': 'Potato'},
 {'id': 'p8', 'name': 'Cassava'},
 {'id': 'p9', 'name': 'Finger Millet'},
 {'id': 'p10', 'name': 'Coconut'},
 {'id': 'p11', 'name': 'Green Gram'},
 {'id': 'p12', 'name': 'Okra'},
 {'id': 'p13', 'name': 'Cowpea'},
 {'id': 'p14', 'name': 'Bitter Gourd'},
 {'id': 'p15', 'name': 'Sweet Potato'},
 {'id': 'p16', 'name': 'Peanut'},
 {'id': 'p17', 'name': 'Black Gram'},
 {'id': 'p18', 'name': 'Soybean'},
 {'id': 'p19', 'name': 'Maize'},
 {'id': 'p20', 'name': 'Pearl Millet'},
 {'id': 'p21', 'name': 'Sorghum'},
 {'id': 'p22', 'name': 'Foxtail Millet'},
 {'id': 'p23', 'name': 'Gotukola'},
 {'id': 'p24', 'name': 'Spinach'},
 {'id': 'p25', 'name': 'Beetroot'},
 {'id': 'p26', 'name': 'Radish'},
 {'id': 'p27', 'name': 'Yam'},
 {'id': 'p28', 'name': 'Cabbage'},
 {'id': 'p29', 'name': 'Carrot'},
 {'id': 'p30', 'name': 'Pumpkin'},
 {'id': 'p31', 'name': 'Cucumber'},
 {'id': 'p32', 'name': 'Watermelon'},
 {'id': 'p33', 'name': 'Papaya'},
 {'id': 'p34', 'name': 'Banana'},
 {'id': 'p35', 'name': 'Garlic'},
 {'id': 'p36', 'name': 'Ginger'},
 {'id': 'p37', 'name': 'Turmeric'},
 {'id': 'p38', 'name': 'Black Pepper'},
 {'id': 'p39', 'name': 'Mango'},
 {'id': 'p40', 'name': 'Lettuce'},
 {'id': 'p41', 'name': 'Cauliflower'},
 {'id': 'p42', 'name': 'Bell Pepper'}]
