"""
Auto-generated comprehensive seed data for plants.
Total records: 70
"""

plants = [ { 'category': 'vegetable',
    'common_name': 'Tomato',
    'description': 'High-value fruit vegetable grown in greenhouse and open field. Rich in lycopene.',
    'id': 'p1',
    'is_active': True,
    'local_name': 'තක්කාලි / தக்காளி',
    'name': 'Tomato',
    'sub_category': 'Solanaceous'},
  { 'category': 'vegetable',
    'common_name': 'Chili',
    'description': 'Essential spice crop with continuous harvesting cycles. High market demand.',
    'id': 'p2',
    'is_active': True,
    'local_name': 'මිරිස් / மிளகாய்',
    'name': 'Chili',
    'sub_category': 'Solanaceous'},
  { 'category': 'grain',
    'common_name': 'Rice',
    'description': 'Primary staple cereal crop cultivated in irrigated wetland and rainfed lowland ecosystems.',
    'id': 'p3',
    'is_active': True,
    'local_name': 'වී / நெல்',
    'name': 'Rice',
    'sub_category': 'Cereal'},
  { 'category': 'vegetable',
    'common_name': 'Brinjal',
    'description': 'Hardy long-duration vegetable producing glossy purple or green fruits across multiple pickings.',
    'id': 'p4',
    'is_active': True,
    'local_name': 'වම්බටු / கத்தரிக்காய்',
    'name': 'Brinjal',
    'sub_category': 'Solanaceous'},
  { 'category': 'vegetable',
    'common_name': 'Beans',
    'description': 'Fast-growing nitrogen-fixing legume producing crisp edible green pods.',
    'id': 'p5',
    'is_active': True,
    'local_name': 'බෝංචි / பீன்ஸ்',
    'name': 'Beans',
    'sub_category': 'Legume'},
  { 'category': 'vegetable',
    'common_name': 'Onion',
    'description': 'High value bulb crop essential for daily culinary consumption.',
    'id': 'p6',
    'is_active': True,
    'local_name': 'ලූනු / வெங்காயம்',
    'name': 'Onion',
    'sub_category': 'Allium'},
  { 'category': 'vegetable',
    'common_name': 'Potato',
    'description': 'Nutrient-dense tuber crop grown extensively in upcountry hill regions.',
    'id': 'p7',
    'is_active': True,
    'local_name': 'අල / உருளைக்கிழங்கு',
    'name': 'Potato',
    'sub_category': 'Tuber'},
  { 'category': 'tuber',
    'common_name': 'Cassava',
    'description': 'Drought-tolerant root tuber providing dietary carbohydrates and industrial starch.',
    'id': 'p8',
    'is_active': True,
    'local_name': 'මඤ්ඤොක්කා / மரவள்ளிக்கிழங்கு',
    'name': 'Cassava',
    'sub_category': 'Root & Tuber'},
  { 'category': 'grain',
    'common_name': 'Finger Millet',
    'description': 'Climate-resilient super-cereal rich in calcium, iron, and dietary fiber.',
    'id': 'p9',
    'is_active': True,
    'local_name': 'කුරක්කන් / குரக்கන්',
    'name': 'Finger Millet',
    'sub_category': 'Millet'},
  { 'category': 'plantation',
    'common_name': 'Coconut',
    'description': 'Perennial plantation palm yielding nuts, oil, copra, and timber.',
    'id': 'p10',
    'is_active': True,
    'local_name': 'පොල් / தேங்காய்',
    'name': 'Coconut',
    'sub_category': 'Palm'},
  { 'category': 'legume',
    'common_name': 'Green Gram',
    'description': 'Short-duration protein-rich pulse crop ideal for dry zone paddy rotation.',
    'id': 'p11',
    'is_active': True,
    'local_name': 'මුං ඇට / பாசிப்பயறு',
    'name': 'Green Gram',
    'sub_category': 'Pulse'},
  { 'category': 'vegetable',
    'common_name': 'Okra',
    'description': 'Continuous-bearing vegetable producing tender mucilaginous pods rich in fiber.',
    'id': 'p12',
    'is_active': True,
    'local_name': 'බණ්ඩක්කා / வெண்டைக்காய்',
    'name': 'Okra',
    'sub_category': 'Malvaceous'},
  { 'category': 'legume',
    'common_name': 'Cowpea',
    'description': 'Drought-hardy legume grown for tender green pods and dried protein seeds.',
    'id': 'p13',
    'is_active': True,
    'local_name': 'කවුපි / தட்டப்பயறு',
    'name': 'Cowpea',
    'sub_category': 'Pulse'},
  { 'category': 'vegetable',
    'common_name': 'Bitter Gourd',
    'description': 'Medicinal vine vegetable with distinct bitter flavor and anti-diabetic compounds.',
    'id': 'p14',
    'is_active': True,
    'local_name': 'කරවිල / பாகற்காய்',
    'name': 'Bitter Gourd',
    'sub_category': 'Cucurbit'},
  { 'category': 'tuber',
    'common_name': 'Sweet Potato',
    'description': 'Fast-maturing sweet tuberous root rich in beta-carotene and vitamins.',
    'id': 'p15',
    'is_active': True,
    'local_name': 'බතල / சர்க்கரைவள்ளிக்கிழங்கு',
    'name': 'Sweet Potato',
    'sub_category': 'Root & Tuber'},
  { 'category': 'legume',
    'common_name': 'Peanut',
    'description': 'Subterranean legume yielding edible nuts rich in healthy fats and protein.',
    'id': 'p16',
    'is_active': True,
    'local_name': 'රටකජු / நிலக்கடலை',
    'name': 'Peanut',
    'sub_category': 'Oilseed'},
  { 'category': 'legume',
    'common_name': 'Black Gram',
    'description': 'Crucial pulse crop for fermented batter products like dosa, hopper, and idli.',
    'id': 'p17',
    'is_active': True,
    'local_name': 'උඳු / உளுந்து',
    'name': 'Black Gram',
    'sub_category': 'Pulse'},
  { 'category': 'legume',
    'common_name': 'Soybean',
    'description': 'High-protein multi-purpose oilseed legume used for livestock feed and food products.',
    'id': 'p18',
    'is_active': True,
    'local_name': 'සෝයා / சோயாபීන්',
    'name': 'Soybean',
    'sub_category': 'Oilseed'},
  { 'category': 'grain',
    'common_name': 'Maize',
    'description': 'Major coarse cereal grain grown for human consumption, animal feed, and silage.',
    'id': 'p19',
    'is_active': True,
    'local_name': 'බඩඉරිඟු / மக்காச்சෝளம்',
    'name': 'Maize',
    'sub_category': 'Cereal'},
  { 'category': 'grain',
    'common_name': 'Pearl Millet',
    'description': 'Extraordinarily drought-tolerant cereal thriving in arid soils and hot climates.',
    'id': 'p20',
    'is_active': True,
    'local_name': 'බජ්රා / கம்பு',
    'name': 'Pearl Millet',
    'sub_category': 'Millet'},
  { 'category': 'grain',
    'common_name': 'Sorghum',
    'description': 'Deep-rooting drought-hardy cereal valuable for grain, fodder, and bio-fuel.',
    'id': 'p21',
    'is_active': True,
    'local_name': 'සොර්ගම් / சோளம்',
    'name': 'Sorghum',
    'sub_category': 'Cereal'},
  { 'category': 'grain',
    'common_name': 'Foxtail Millet',
    'description': 'Ancient small-seeded millet rich in minerals, gluten-free and easily digestible.',
    'id': 'p22',
    'is_active': True,
    'local_name': 'තණහාල් / தினை',
    'name': 'Foxtail Millet',
    'sub_category': 'Millet'},
  { 'category': 'vegetable',
    'common_name': 'Gotukola',
    'description': 'Valuable medicinal leafy green herb promoting memory retention and overall vitality.',
    'id': 'p23',
    'is_active': True,
    'local_name': 'ගොටුකොළ / வல்லாரை',
    'name': 'Gotukola',
    'sub_category': 'Leafy Green'},
  { 'category': 'vegetable',
    'common_name': 'Spinach',
    'description': 'Fast growing succulent leafy green loaded with vitamins, iron, and antioxidants.',
    'id': 'p24',
    'is_active': True,
    'local_name': 'නිවිති / பசளி',
    'name': 'Spinach',
    'sub_category': 'Leafy Green'},
  { 'category': 'vegetable',
    'common_name': 'Beetroot',
    'description': 'Vibrant crimson taproot vegetable rich in nitrates, folate, and sweetness.',
    'id': 'p25',
    'is_active': True,
    'local_name': 'බීට්රූට් / பீட்ரூட்',
    'name': 'Beetroot',
    'sub_category': 'Root'},
  { 'category': 'vegetable',
    'common_name': 'Radish',
    'description': 'Fast-growing crisp pungent white root vegetable ready for early harvest.',
    'id': 'p26',
    'is_active': True,
    'local_name': 'රාබු / முள்ளங்கி',
    'name': 'Radish',
    'sub_category': 'Root'},
  { 'category': 'tuber',
    'common_name': 'Yam',
    'description': 'Nutritious edible corm tuber with delicious earthy texture and high market demand.',
    'id': 'p27',
    'is_active': True,
    'local_name': 'ඉන්නල / கருணைக்கிழங்கு',
    'name': 'Yam',
    'sub_category': 'Root & Tuber'},
  { 'category': 'vegetable',
    'common_name': 'Cabbage',
    'description': 'Cool-climate brassica forming dense solid round heads packed with vitamins.',
    'id': 'p28',
    'is_active': True,
    'local_name': 'ගෝවා / முட்டைக்கோஸ்',
    'name': 'Cabbage',
    'sub_category': 'Cruciferous'},
  { 'category': 'vegetable',
    'common_name': 'Carrot',
    'description': 'Sweet crunchy orange taproot rich in beta carotene and dietary fiber.',
    'id': 'p29',
    'is_active': True,
    'local_name': 'කැරට් / கேரட்',
    'name': 'Carrot',
    'sub_category': 'Root'},
  { 'category': 'vegetable',
    'common_name': 'Pumpkin',
    'description': 'Long-storing trailing cucurbit fruit with rich orange carotenoid-rich flesh.',
    'id': 'p30',
    'is_active': True,
    'local_name': 'වට්ටක්කා / பூசணிக்காய்',
    'name': 'Pumpkin',
    'sub_category': 'Cucurbit'},
  { 'category': 'vegetable',
    'common_name': 'Cucumber',
    'description': 'Crisp refreshing cylindrical fruit with high water content and rapid growth.',
    'id': 'p31',
    'is_active': True,
    'local_name': 'පිපිඤ්ඤා / வெள்ளரிக்காய்',
    'name': 'Cucumber',
    'sub_category': 'Cucurbit'},
  { 'category': 'fruit',
    'common_name': 'Watermelon',
    'description': 'Juicy thirst-quenching dessert melon packed with lycopene and sweet sugars.',
    'id': 'p32',
    'is_active': True,
    'local_name': 'කොමඩු / தர்பூசணி',
    'name': 'Watermelon',
    'sub_category': 'Cucurbit'},
  { 'category': 'fruit',
    'common_name': 'Papaya',
    'description': 'Fast-bearing herbaceous fruit tree producing sweet orange melon-like fruit.',
    'id': 'p33',
    'is_active': True,
    'local_name': 'පැපොල් / பப்பாளி',
    'name': 'Papaya',
    'sub_category': 'Tropical'},
  { 'category': 'fruit',
    'common_name': 'Banana',
    'description': 'Perennial giant herbaceous crop bearing nutritious sweet heavy fruit bunches.',
    'id': 'p34',
    'is_active': True,
    'local_name': 'කෙසෙල් / வாழைப்பழம்',
    'name': 'Banana',
    'sub_category': 'Tropical'},
  { 'category': 'spice',
    'common_name': 'Garlic',
    'description': 'Pungent aromatic bulb containing allicin with potent culinary and antimicrobial value.',
    'id': 'p35',
    'is_active': True,
    'local_name': 'සුදුලූනු / பூண்டு',
    'name': 'Garlic',
    'sub_category': 'Allium'},
  { 'category': 'spice',
    'common_name': 'Ginger',
    'description': 'Valuable pungent rhizome crop widely used in spices, beverages, and traditional remedies.',
    'id': 'p36',
    'is_active': True,
    'local_name': 'ඉඟුරු / இஞ்சி',
    'name': 'Ginger',
    'sub_category': 'Rhizome'},
  { 'category': 'spice',
    'common_name': 'Turmeric',
    'description': 'Golden rhizome loaded with curcumin, potent anti-inflammatory and vibrant spice.',
    'id': 'p37',
    'is_active': True,
    'local_name': 'කහ / மஞ்சள்',
    'name': 'Turmeric',
    'sub_category': 'Rhizome'},
  { 'category': 'spice',
    'common_name': 'Black Pepper',
    'description': 'King of spices; perennial climbing woody vine producing pungent berry spikes.',
    'id': 'p38',
    'is_active': True,
    'local_name': 'ගම්මිරිස් / மிளகு',
    'name': 'Black Pepper',
    'sub_category': 'Plantation'},
  { 'category': 'fruit',
    'common_name': 'Mango',
    'description': 'King of tropical fruits; evergreen tree bearing succulent fragrant sweet drupes.',
    'id': 'p39',
    'is_active': True,
    'local_name': 'අඹ / மாம்பழம்',
    'name': 'Mango',
    'sub_category': 'Tropical'},
  { 'category': 'vegetable',
    'common_name': 'Lettuce',
    'description': 'Crisp cool-season salad green for fresh culinary consumption and hydroponics.',
    'id': 'p40',
    'is_active': True,
    'local_name': 'සලාද කොළ / கீரைவகை',
    'name': 'Lettuce',
    'sub_category': 'Leafy Green'},
  { 'category': 'vegetable',
    'common_name': 'Cauliflower',
    'description': 'Prized brassica forming dense white curd heads rich in antioxidants and vitamins.',
    'id': 'p41',
    'is_active': True,
    'local_name': 'මල් ගෝවා / காலிஃபிளவர்',
    'name': 'Cauliflower',
    'sub_category': 'Cruciferous'},
  { 'category': 'vegetable',
    'common_name': 'Bell Pepper',
    'description': 'Sweet blocky thick-walled capsicum grown in open fields and greenhouses.',
    'id': 'p42',
    'is_active': True,
    'local_name': 'මාළු මිරිස් / குடைமிளகாய்',
    'name': 'Bell Pepper',
    'sub_category': 'Solanaceous'},
  { 'category': 'fruit',
    'common_name': 'Pineapple',
    'description': 'Bromeliad fruit with juicy sweet-sour flesh rich in bromelain enzyme.',
    'id': 'p43',
    'is_active': True,
    'local_name': 'අන්නාසි / அன்னாசி',
    'name': 'Pineapple',
    'sub_category': 'Tropical'},
  { 'category': 'cash_crop',
    'common_name': 'Sugarcane',
    'description': 'Tall perennial grass with thick juicy stalks cultivated for sugar, jaggery, and ethanol.',
    'id': 'p44',
    'is_active': True,
    'local_name': 'උක් / கரும்பு',
    'name': 'Sugarcane',
    'sub_category': 'Industrial'},
  { 'category': 'plantation',
    'common_name': 'Tea',
    'description': 'Evergreen perennial shrub grown for tender top flush of leaves (two leaves and a bud).',
    'id': 'p45',
    'is_active': True,
    'local_name': 'තේ / தேயிலை',
    'name': 'Tea',
    'sub_category': 'Beverage'},
  { 'category': 'plantation',
    'common_name': 'Coffee',
    'description': 'Evergreen woody shrub bearing berries with caffeine-rich beans for brewing.',
    'id': 'p46',
    'is_active': True,
    'local_name': 'කෝපි / காப்பி',
    'name': 'Coffee',
    'sub_category': 'Beverage'},
  { 'category': 'spice',
    'common_name': 'Cinnamon',
    'description': 'Prized fragrant spice derived from the inner bark of evergreen tree.',
    'id': 'p47',
    'is_active': True,
    'local_name': 'කුරුඳු / இலவங்கப்பட்டை',
    'name': 'Cinnamon',
    'sub_category': 'Plantation'},
  { 'category': 'spice',
    'common_name': 'Cardamom',
    'description': 'Queen of Spices; shade-loving perennial yielding highly aromatic dried tri-locular pods.',
    'id': 'p48',
    'is_active': True,
    'local_name': 'එනසාල් / ஏலக்காய்',
    'name': 'Cardamom',
    'sub_category': 'Plantation'},
  { 'category': 'plantation',
    'common_name': 'Cashew',
    'description': 'Tropical evergreen tree producing sweet cashew apples and valuable kidney-shaped nuts.',
    'id': 'p49',
    'is_active': True,
    'local_name': 'කජු / முந்திரி',
    'name': 'Cashew',
    'sub_category': 'Nut'},
  { 'category': 'plantation',
    'common_name': 'Cocoa',
    'description': 'Shade-loving small tree yielding pods filled with beans for chocolate and cocoa butter.',
    'id': 'p50',
    'is_active': True,
    'local_name': 'කොකෝවා / கொக்கோ',
    'name': 'Cocoa',
    'sub_category': 'Cash Crop'},
  { 'category': 'fruit',
    'common_name': 'Guava',
    'description': 'Hardy tropical shrub bearing fragrant vitamin C-rich fruit with crisp edible flesh.',
    'id': 'p51',
    'is_active': True,
    'local_name': 'පේර / கொய்யா',
    'name': 'Guava',
    'sub_category': 'Tropical'},
  { 'category': 'fruit',
    'common_name': 'Lime',
    'description': 'Thorny citrus shrub producing intensely sour vitamin C-rich juice fruits.',
    'id': 'p52',
    'is_active': True,
    'local_name': 'දෙහි / எலுமிச்சை',
    'name': 'Lime',
    'sub_category': 'Citrus'},
  { 'category': 'fruit',
    'common_name': 'Sweet Orange',
    'description': 'Subtropical citrus tree bearing juicy sweet segments packed with Vitamin C.',
    'id': 'p53',
    'is_active': True,
    'local_name': 'දොඩම් / ஆரஞ்சு',
    'name': 'Sweet Orange',
    'sub_category': 'Citrus'},
  { 'category': 'fruit',
    'common_name': 'Pomegranate',
    'description': 'Drought-hardy fruit shrub producing jewel-like ruby arils packed with polyphenols.',
    'id': 'p54',
    'is_active': True,
    'local_name': 'දෙළුම් / மாதுளை',
    'name': 'Pomegranate',
    'sub_category': 'Subtropical'},
  { 'category': 'fruit',
    'common_name': 'Strawberry',
    'description': 'High-value temperate berry cultivated in upcountry tunnels for sweet red berries.',
    'id': 'p55',
    'is_active': True,
    'local_name': 'ස්ට්\u200dරෝබෙරි / ஸ்ட்ராபெர்ரி',
    'name': 'Strawberry',
    'sub_category': 'Berry'},
  { 'category': 'fruit',
    'common_name': 'Dragon Fruit',
    'description': 'Climbing cactus producing vibrant scaly exotic fruit rich in antioxidants.',
    'id': 'p56',
    'is_active': True,
    'local_name': 'ඩ්\u200dරැගන් ෆෲට් / டிராகன் பழம்',
    'name': 'Dragon Fruit',
    'sub_category': 'Exotic'},
  { 'category': 'fruit',
    'common_name': 'Passion Fruit',
    'description': 'Vigorous perennial climbing vine bearing aromatic tart-sweet purple or yellow fruits.',
    'id': 'p57',
    'is_active': True,
    'local_name': 'වැල් දොඩම් / கொடித்தோடை',
    'name': 'Passion Fruit',
    'sub_category': 'Vine'},
  { 'category': 'vegetable',
    'common_name': 'Snake Gourd',
    'description': 'Trellised climbing vine producing long slender green striped edible fruits.',
    'id': 'p58',
    'is_active': True,
    'local_name': 'පතෝල / புடலங்காய்',
    'name': 'Snake Gourd',
    'sub_category': 'Cucurbit'},
  { 'category': 'vegetable',
    'common_name': 'Ridge Gourd',
    'description': 'Hardy cucurbit vine bearing club-shaped fruits with prominent sharp longitudinal ribs.',
    'id': 'p59',
    'is_active': True,
    'local_name': 'වැටකොළු / பீர்க்கங்காய்',
    'name': 'Ridge Gourd',
    'sub_category': 'Cucurbit'},
  { 'category': 'vegetable',
    'common_name': 'Bottle Gourd',
    'description': 'Vigorous trailing vine producing large light-green bottle-shaped edible gourds.',
    'id': 'p60',
    'is_active': True,
    'local_name': 'දියලබු / சுரைக்காய்',
    'name': 'Bottle Gourd',
    'sub_category': 'Cucurbit'},
  { 'category': 'vegetable',
    'common_name': 'Moringa',
    'description': 'Fast-growing miracle tree producing nutrient-dense leaves and tender edible pods.',
    'id': 'p61',
    'is_active': True,
    'local_name': 'මුරුංගා / முருங்கை',
    'name': 'Moringa',
    'sub_category': 'Superfood'},
  { 'category': 'herb',
    'common_name': 'Curry Leaves',
    'description': 'Aromatic shrub yielding fresh pinnate leaves indispensable in South Asian cooking.',
    'id': 'p62',
    'is_active': True,
    'local_name': 'කරපිංචා / கறிவேப்பிலை',
    'name': 'Curry Leaves',
    'sub_category': 'Spice'},
  { 'category': 'herb',
    'common_name': 'Coriander',
    'description': 'Fast-growing annual herb yielding fragrant cilantro leaves and dried spice seeds.',
    'id': 'p63',
    'is_active': True,
    'local_name': 'කොත්තමල්ලි / கொத்தமல்லி',
    'name': 'Coriander',
    'sub_category': 'Spice'},
  { 'category': 'herb',
    'common_name': 'Mint',
    'description': 'Fast spreading aromatic perennial herb prized for refreshing menthol leaves.',
    'id': 'p64',
    'is_active': True,
    'local_name': 'මිංචි / புதினா',
    'name': 'Mint',
    'sub_category': 'Aromatic'},
  { 'category': 'grain',
    'common_name': 'Sesame',
    'description': 'Ancient drought-tolerant oilseed producing tiny oil-rich white or black seeds.',
    'id': 'p65',
    'is_active': True,
    'local_name': 'තල / எள்ளු',
    'name': 'Sesame',
    'sub_category': 'Oilseed'},
  { 'category': 'spice',
    'common_name': 'Mustard',
    'description': 'Fast-growing brassica spice yielding pungent tiny seeds for tempering and oils.',
    'id': 'p66',
    'is_active': True,
    'local_name': 'අබ / கடுகு',
    'name': 'Mustard',
    'sub_category': 'Oilseed'},
  { 'category': 'cash_crop',
    'common_name': 'Cotton',
    'description': 'Industrial fiber crop yielding natural white cotton bolls for textile manufacturing.',
    'id': 'p67',
    'is_active': True,
    'local_name': 'කපු / பருத்தி',
    'name': 'Cotton',
    'sub_category': 'Fiber'},
  { 'category': 'grain',
    'common_name': 'Wheat',
    'description': "World's leading cereal grain producing flour for bread, pasta, and baked goods.",
    'id': 'p68',
    'is_active': True,
    'local_name': 'තිරිඟු / கோதுமை',
    'name': 'Wheat',
    'sub_category': 'Cereal'},
  { 'category': 'legume',
    'common_name': 'Chickpea',
    'description': 'Protein-dense pulse crop producing nutritious nutty seeds for culinary consumption.',
    'id': 'p69',
    'is_active': True,
    'local_name': 'කඩල / கொண்டைக்கடலை',
    'name': 'Chickpea',
    'sub_category': 'Pulse'},
  { 'category': 'vegetable',
    'common_name': 'Broccoli',
    'description': 'Nutrient-packed brassica producing dense emerald-green edible flower heads.',
    'id': 'p70',
    'is_active': True,
    'local_name': 'බ්\u200dරොකොලි / பிராக்கோலி',
    'name': 'Broccoli',
    'sub_category': 'Cruciferous'}]
