"""
Auto-generated comprehensive seed data for pruning_guides.
Total records: 138
"""

pruning_guides = [ { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative '
                      'Branching.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's3',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & Fruit '
                      'Setting.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's4',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit '
                      'Enlargement.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's5',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative '
                      'Branching.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's9',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & Fruit '
                      'Setting.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's10',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit '
                      'Enlargement.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's11',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative '
                      'Branching.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's21',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & Fruit '
                      'Setting.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's22',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit '
                      'Enlargement.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's23',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative '
                      'Growth.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's27',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Formation.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's28',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Maturation & '
                      'Development.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's29',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative '
                      'Canopy.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's39',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Tuber Initiation.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's40',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Tuber Bulking.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's41',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative '
                      'Canopy.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's45',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Tuber Initiation.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's46',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Tuber Bulking.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's47',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Canopy '
                      'Architecture.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's57',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Flush.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's58',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Crop Maturation.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's59',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative '
                      'Growth.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's69',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Formation.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's70',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Maturation & '
                      'Development.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's71',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Trellising.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's81',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Setting & '
                      'Expansion.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's82',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Maturity.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's83',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative '
                      'Canopy.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's87',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Tuber Initiation.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's88',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Tuber Bulking.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's89',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Rapid Leaf '
                      'Expansion.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's135',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Canopy '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's136',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Prime Foliage '
                      'Maturity.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's137',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Rapid Leaf '
                      'Expansion.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's141',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Canopy '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's142',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Prime Foliage '
                      'Maturity.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's143',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative '
                      'Canopy.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's159',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Tuber Initiation.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's160',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Tuber Bulking.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's161',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Trellising.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's177',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Setting & '
                      'Expansion.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's178',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Maturity.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's179',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Trellising.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's183',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Setting & '
                      'Expansion.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's184',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Maturity.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's185',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Trellising.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's189',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Setting & '
                      'Expansion.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's190',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Maturity.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's191',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & Fruit '
                      'Set.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's195',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Growth & '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's196',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Ripening.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's197',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & Fruit '
                      'Set.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's201',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Growth & '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's202',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Ripening.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's203',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative Shoot '
                      'Growth.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's213',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Rhizome / Berry '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's214',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Maturation.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's215',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative Shoot '
                      'Growth.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's219',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Rhizome / Berry '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's220',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Maturation.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's221',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative Shoot '
                      'Growth.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's225',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Rhizome / Berry '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's226',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Maturation.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's227',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & Fruit '
                      'Set.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's231',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Growth & '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's232',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Ripening.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's233',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Rapid Leaf '
                      'Expansion.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's237',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Canopy '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's238',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Prime Foliage '
                      'Maturity.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's239',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative '
                      'Branching.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's249',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & Fruit '
                      'Setting.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's250',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit '
                      'Enlargement.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's251',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & Fruit '
                      'Set.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's255',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Growth & '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's256',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Ripening.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's257',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Canopy '
                      'Architecture.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's267',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Flush.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's268',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Crop Maturation.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's269',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Canopy '
                      'Architecture.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's273',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Flush.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's274',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Crop Maturation.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's275',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative Shoot '
                      'Growth.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's279',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Rhizome / Berry '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's280',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Maturation.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's281',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative Shoot '
                      'Growth.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's285',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Rhizome / Berry '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's286',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Maturation.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's287',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Canopy '
                      'Architecture.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's291',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Flush.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's292',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Crop Maturation.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's293',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Canopy '
                      'Architecture.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's297',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Flush.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's298',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Crop Maturation.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's299',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & Fruit '
                      'Set.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's303',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Growth & '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's304',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Ripening.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's305',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & Fruit '
                      'Set.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's309',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Growth & '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's310',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Ripening.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's311',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & Fruit '
                      'Set.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's315',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Growth & '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's316',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Ripening.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's317',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & Fruit '
                      'Set.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's321',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Growth & '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's322',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Ripening.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's323',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & Fruit '
                      'Set.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's327',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Growth & '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's328',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Ripening.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's329',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & Fruit '
                      'Set.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's333',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Growth & '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's334',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Ripening.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's335',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & Fruit '
                      'Set.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's339',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Growth & '
                      'Development.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's340',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Ripening.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's341',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Trellising.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's345',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Setting & '
                      'Expansion.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's346',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Maturity.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's347',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Trellising.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's351',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Setting & '
                      'Expansion.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's352',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Maturity.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's353',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Trellising.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's357',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Setting & '
                      'Expansion.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's358',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Fruit Maturity.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's359',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative '
                      'Growth.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's363',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Formation.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's364',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Maturation & '
                      'Development.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's365',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative '
                      'Growth.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's369',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Formation.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's370',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Maturation & '
                      'Development.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's371',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative '
                      'Growth.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's381',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Formation.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's382',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Maturation & '
                      'Development.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's383',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Vegetative '
                      'Growth.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's399',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Flowering & '
                      'Formation.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's400',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Maturation & '
                      'Development.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's401',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 7,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Foliage '
                      'Development.',
    'pruning_type': 'desuckering',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's417',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Head / Curd '
                      'Initiation.',
    'pruning_type': 'thinning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's418',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5},
  { 'frequency_days': 14,
    'importance': 'recommended',
    'post_pruning': 'Apply light copper-based or neem protective spray on cut surfaces.',
    'pre_pruning': 'Sterilize tools with 70% alcohol and prune on dry sunny mornings.',
    'pruning_method': 'Remove redundant side shoots, diseased leaves, and overcrowded foliage during Head Enlargement.',
    'pruning_type': 'sanitary_pruning',
    'season_notes': 'Avoid pruning during heavy continuous rain.',
    'stage_id': 's419',
    'tools_needed': 'Sharp bypass pruners / sanitised secateurs',
    'trigger_day': 5}]
