varieties = [{'plant_id': 'p1',
  'variety_name': 'Roma',
  'description': 'Plum tomato, thick flesh, ideal for sauces and paste.',
  'scientific_name': 'Solanum lycopersicum',
  'growth_duration_days': 90,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p1',
  'variety_name': 'Cherry',
  'description': 'Small, sweet fruit; high-yielding and quick to mature.',
  'scientific_name': 'Solanum lycopersicum',
  'growth_duration_days': 90,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p1',
  'variety_name': 'Beefsteak',
  'description': 'Large, juicy fruit for fresh market.',
  'scientific_name': 'Solanum lycopersicum',
  'growth_duration_days': 90,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p2',
  'variety_name': 'Red Hot',
  'description': 'High pungency cayenne type for drying.',
  'scientific_name': 'Capsicum frutescens',
  'growth_duration_days': 120,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p2',
  'variety_name': "Bird's Eye",
  'description': 'Small very hot pods, popular for spice powder.',
  'scientific_name': 'Capsicum frutescens',
  'growth_duration_days': 120,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p3',
  'variety_name': 'Samba',
  'description': 'Short-grain, hard texture, suited to dry-zone paddies.',
  'scientific_name': 'Oryza sativa',
  'growth_duration_days': 150,
  'optimal_ph_min': 5.0,
  'optimal_ph_max': 6.5},
 {'plant_id': 'p3',
  'variety_name': 'Nadu',
  'description': 'Medium-grain all-purpose variety.',
  'scientific_name': 'Oryza sativa',
  'growth_duration_days': 150,
  'optimal_ph_min': 5.0,
  'optimal_ph_max': 6.5},
 {'plant_id': 'p3',
  'variety_name': 'Basmati',
  'description': 'Long-grain fragrant rice.',
  'scientific_name': 'Oryza sativa',
  'growth_duration_days': 150,
  'optimal_ph_min': 5.0,
  'optimal_ph_max': 6.5},
 {'plant_id': 'p4',
  'variety_name': 'Long Purple',
  'description': 'Elongated purple fruit, high yield.',
  'scientific_name': 'Solanum melongena',
  'growth_duration_days': 110,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p4',
  'variety_name': 'Round Green',
  'description': 'Round green-white fruit, mild flavor.',
  'scientific_name': 'Solanum melongena',
  'growth_duration_days': 110,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p5',
  'variety_name': 'Bush Bean',
  'description': 'Compact, no staking needed; quick harvest.',
  'scientific_name': 'Phaseolus vulgaris',
  'growth_duration_days': 70,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p5',
  'variety_name': 'Pole Bean',
  'description': 'Climbing type, longer harvest window.',
  'scientific_name': 'Phaseolus vulgaris',
  'growth_duration_days': 70,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p6',
  'variety_name': 'Red Onion',
  'description': 'Pungent red bulbs, good storage.',
  'scientific_name': 'Allium cepa',
  'growth_duration_days': 120,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 7.5},
 {'plant_id': 'p6',
  'variety_name': 'Big Onion',
  'description': 'Large yellow-brown bulbs for fresh market.',
  'scientific_name': 'Allium cepa',
  'growth_duration_days': 120,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 7.5},
 {'plant_id': 'p7',
  'variety_name': 'Granola',
  'description': 'Yellow skin/lesh, versatile table potato.',
  'scientific_name': 'Solanum tuberosum',
  'growth_duration_days': 100,
  'optimal_ph_min': 5.2,
  'optimal_ph_max': 6.5},
 {'plant_id': 'p7',
  'variety_name': 'Desiree',
  'description': 'Red skin, high yielding.',
  'scientific_name': 'Solanum tuberosum',
  'growth_duration_days': 100,
  'optimal_ph_min': 5.2,
  'optimal_ph_max': 6.5},
 {'plant_id': 'p8',
  'variety_name': 'Mukunuwenna',
  'description': 'Local high-yielding bitter type.',
  'scientific_name': 'Manihot esculenta',
  'growth_duration_days': 240,
  'optimal_ph_min': 5.0,
  'optimal_ph_max': 6.5},
 {'plant_id': 'p8',
  'variety_name': 'Sweet Cassava',
  'description': 'Low-cyanide sweet variety.',
  'scientific_name': 'Manihot esculenta',
  'growth_duration_days': 240,
  'optimal_ph_min': 5.0,
  'optimal_ph_max': 6.5},
 {'plant_id': 'p9',
  'variety_name': 'Local Ragi',
  'description': 'Traditional variety, drought tolerant.',
  'scientific_name': 'Eleusine coracana',
  'growth_duration_days': 105,
  'optimal_ph_min': 5.0,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p10',
  'variety_name': 'Tall Typica',
  'description': 'Classic tall coconut, long productive life.',
  'scientific_name': 'Cocos nucifera',
  'growth_duration_days': 365,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p10',
  'variety_name': 'Dwarf',
  'description': 'Shorter, earlier-bearing hybrid.',
  'scientific_name': 'Cocos nucifera',
  'growth_duration_days': 365,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p11',
  'variety_name': 'Local Mung',
  'description': 'Short-season pulse, nitrogen fixing.',
  'scientific_name': 'Vigna radiata',
  'growth_duration_days': 70,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p12',
  'variety_name': 'Green Smooth',
  'description': 'Smooth green pods, tender when young.',
  'scientific_name': 'Abelmoschus esculentus',
  'growth_duration_days': 90,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p12',
  'variety_name': 'Red Spine',
  'description': 'Reddish stems, robust grower.',
  'scientific_name': 'Abelmoschus esculentus',
  'growth_duration_days': 90,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p13',
  'variety_name': 'Bush Cowpea',
  'description': 'Bushy, early-maturing grain/forage type.',
  'scientific_name': 'Vigna unguiculata',
  'growth_duration_days': 90,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 6.5},
 {'plant_id': 'p14',
  'variety_name': 'White Bitter',
  'description': 'Pale, long fruit; milder bitterness.',
  'scientific_name': 'Momordica charantia',
  'growth_duration_days': 120,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p15',
  'variety_name': 'Orange Flesh',
  'description': 'Sweet orange flesh, rich in carotene.',
  'scientific_name': 'Ipomoea batatas',
  'growth_duration_days': 120,
  'optimal_ph_min': 5.6,
  'optimal_ph_max': 6.6},
 {'plant_id': 'p15',
  'variety_name': 'White Flesh',
  'description': 'Drier starchy white flesh.',
  'scientific_name': 'Ipomoea batatas',
  'growth_duration_days': 120,
  'optimal_ph_min': 5.6,
  'optimal_ph_max': 6.6},
 {'plant_id': 'p16',
  'variety_name': 'Virginia',
  'description': 'Large-seeded bunch type.',
  'scientific_name': 'Arachis hypogaea',
  'growth_duration_days': 110,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 6.5},
 {'plant_id': 'p17',
  'variety_name': 'Local Urad',
  'description': 'Traditional black gram, short season.',
  'scientific_name': 'Vigna mungo',
  'growth_duration_days': 80,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p18',
  'variety_name': 'Yellow Soybean',
  'description': 'Standard oilseed/forage variety.',
  'scientific_name': 'Glycine max',
  'growth_duration_days': 100,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p19',
  'variety_name': 'Hybrid Yellow',
  'description': 'High-yielding yellow grain hybrid.',
  'scientific_name': 'Zea mays',
  'growth_duration_days': 110,
  'optimal_ph_min': 5.8,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p19',
  'variety_name': 'Open-Pollinated White',
  'description': 'White grain, seed-savable.',
  'scientific_name': 'Zea mays',
  'growth_duration_days': 110,
  'optimal_ph_min': 5.8,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p20',
  'variety_name': 'Local Kurakkan',
  'description': 'Heat- and drought-tolerant local type.',
  'scientific_name': 'Pennisetum glaucum',
  'growth_duration_days': 90,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 7.5},
 {'plant_id': 'p21',
  'variety_name': 'Grain Sorghum',
  'description': 'Dual-purpose grain/forage.',
  'scientific_name': 'Sorghum bicolor',
  'growth_duration_days': 110,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 7.5},
 {'plant_id': 'p22',
  'variety_name': 'Local Thinai',
  'description': 'Short-season millet for dry zones.',
  'scientific_name': 'Setaria italica',
  'growth_duration_days': 90,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p23',
  'variety_name': 'Local Gotukola',
  'description': 'Perennial leafy green, cut-and-come-again.',
  'scientific_name': 'Centella asiatica',
  'growth_duration_days': 90,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 7.5},
 {'plant_id': 'p24',
  'variety_name': 'Bloomsdale',
  'description': 'Savoy-leaf spinach, heat tolerant.',
  'scientific_name': 'Spinacia oleracea',
  'growth_duration_days': 50,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p24',
  'variety_name': 'Malabar Spinach',
  'description': 'Vining heat-loving spinach substitute.',
  'scientific_name': 'Spinacia oleracea',
  'growth_duration_days': 50,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p25',
  'variety_name': 'Detroit',
  'description': 'Round dark-red roots, reliable cropper.',
  'scientific_name': 'Beta vulgaris',
  'growth_duration_days': 75,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p26',
  'variety_name': 'White Icicle',
  'description': 'Long white crisp roots.',
  'scientific_name': 'Raphanus sativus',
  'growth_duration_days': 45,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p26',
  'variety_name': 'Cherry Belle',
  'description': 'Round red quick-maturing roots.',
  'scientific_name': 'Raphanus sativus',
  'growth_duration_days': 45,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p27',
  'variety_name': 'Lesser Yam',
  'description': 'Local lesser yam, starchy tubers.',
  'scientific_name': 'Dioscorea alata',
  'growth_duration_days': 240,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 6.5},
 {'plant_id': 'p28',
  'variety_name': 'Green Cabbage',
  'description': 'Standard firm green heads.',
  'scientific_name': 'Brassica oleracea',
  'growth_duration_days': 100,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p28',
  'variety_name': 'Red Cabbage',
  'description': 'Deep red-purple leaves, sweet flavor.',
  'scientific_name': 'Brassica oleracea',
  'growth_duration_days': 100,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p29',
  'variety_name': 'Nantes',
  'description': 'Cylindrical, sweet, and crisp.',
  'scientific_name': 'Daucus carota',
  'growth_duration_days': 75,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p29',
  'variety_name': 'Kuroda',
  'description': 'Heat tolerant, good for tropical regions.',
  'scientific_name': 'Daucus carota',
  'growth_duration_days': 75,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p30',
  'variety_name': 'Sugar Pumpkin',
  'description': 'Small, sweet, excellent for cooking.',
  'scientific_name': 'Cucurbita pepo',
  'growth_duration_days': 110,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p30',
  'variety_name': 'Giant Pumpkin',
  'description': 'Large variety, high yield.',
  'scientific_name': 'Cucurbita pepo',
  'growth_duration_days': 110,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p31',
  'variety_name': 'Slicing Cucumber',
  'description': 'Long, dark green, good for salads.',
  'scientific_name': 'Cucumis sativus',
  'growth_duration_days': 60,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p31',
  'variety_name': 'Pickling Cucumber',
  'description': 'Small, bumpy skin, ideal for pickling.',
  'scientific_name': 'Cucumis sativus',
  'growth_duration_days': 60,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p32',
  'variety_name': 'Sugar Baby',
  'description': 'Small, very sweet, dark green rind.',
  'scientific_name': 'Citrullus lanatus',
  'growth_duration_days': 90,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p32',
  'variety_name': 'Crimson Sweet',
  'description': 'Large, striped, excellent flavor.',
  'scientific_name': 'Citrullus lanatus',
  'growth_duration_days': 90,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p33',
  'variety_name': 'Red Lady',
  'description': 'Dwarf, early bearing, sweet red flesh.',
  'scientific_name': 'Carica papaya',
  'growth_duration_days': 270,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 6.5},
 {'plant_id': 'p33',
  'variety_name': 'Solo',
  'description': 'Small, sweet fruit, yellow-orange flesh.',
  'scientific_name': 'Carica papaya',
  'growth_duration_days': 270,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 6.5},
 {'plant_id': 'p34',
  'variety_name': 'Cavendish',
  'description': 'Standard dessert banana, high yield.',
  'scientific_name': 'Musa spp.',
  'growth_duration_days': 365,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p34',
  'variety_name': 'Red Banana',
  'description': 'Red skin, sweet creamy flesh.',
  'scientific_name': 'Musa spp.',
  'growth_duration_days': 365,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p35',
  'variety_name': 'Softneck',
  'description': 'Standard white garlic, stores well.',
  'scientific_name': 'Allium sativum',
  'growth_duration_days': 120,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p35',
  'variety_name': 'Hardneck',
  'description': 'Stronger flavor, produces scapes.',
  'scientific_name': 'Allium sativum',
  'growth_duration_days': 120,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p36',
  'variety_name': 'Local Ginger',
  'description': 'Pungent and fibrous.',
  'scientific_name': 'Zingiber officinale',
  'growth_duration_days': 240,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 6.5},
 {'plant_id': 'p36',
  'variety_name': 'Giant Ginger',
  'description': 'Large rhizomes, less fibrous.',
  'scientific_name': 'Zingiber officinale',
  'growth_duration_days': 240,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 6.5},
 {'plant_id': 'p37',
  'variety_name': 'Local Turmeric',
  'description': 'High curcumin content, deep orange.',
  'scientific_name': 'Curcuma longa',
  'growth_duration_days': 240,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 6.5},
 {'plant_id': 'p38',
  'variety_name': 'Panniyur',
  'description': 'High yielding, long spikes.',
  'scientific_name': 'Piper nigrum',
  'growth_duration_days': 365,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 6.5},
 {'plant_id': 'p38',
  'variety_name': 'Karimunda',
  'description': 'Popular traditional variety, adaptable.',
  'scientific_name': 'Piper nigrum',
  'growth_duration_days': 365,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 6.5},
 {'plant_id': 'p39',
  'variety_name': 'Alphonso',
  'description': 'Rich, sweet, premium quality.',
  'scientific_name': 'Mangifera indica',
  'growth_duration_days': 365,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 7.5},
 {'plant_id': 'p39',
  'variety_name': 'Tommy Atkins',
  'description': 'Disease resistant, long shelf life.',
  'scientific_name': 'Mangifera indica',
  'growth_duration_days': 365,
  'optimal_ph_min': 5.5,
  'optimal_ph_max': 7.5},
 {'plant_id': 'p40',
  'variety_name': 'Iceberg',
  'description': 'Crisp heads, heat sensitive.',
  'scientific_name': 'Lactuca sativa',
  'growth_duration_days': 50,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p40',
  'variety_name': 'Butterhead',
  'description': 'Soft leaves, sweet flavor.',
  'scientific_name': 'Lactuca sativa',
  'growth_duration_days': 50,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 7.0},
 {'plant_id': 'p41',
  'variety_name': 'Snowball',
  'description': 'Classic white heads.',
  'scientific_name': 'Brassica oleracea',
  'growth_duration_days': 90,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p41',
  'variety_name': 'Tropical White',
  'description': 'Heat tolerant variety.',
  'scientific_name': 'Brassica oleracea',
  'growth_duration_days': 90,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p42',
  'variety_name': 'California Wonder',
  'description': 'Blocky, thick-walled, green to red.',
  'scientific_name': 'Capsicum annuum',
  'growth_duration_days': 90,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 6.8},
 {'plant_id': 'p42',
  'variety_name': 'Yellow Wonder',
  'description': 'Sweet, turns yellow when ripe.',
  'scientific_name': 'Capsicum annuum',
  'growth_duration_days': 90,
  'optimal_ph_min': 6.0,
  'optimal_ph_max': 6.8}]
