"""
Auto-generated comprehensive seed data for water_requirements.
Total records: 420
"""

water_requirements = [ { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p1',
    'stage_id': 's1',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p1',
    'stage_id': 's2',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p1',
    'stage_id': 's3',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p1',
    'stage_id': 's4',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p1',
    'stage_id': 's5',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p1',
    'stage_id': 's6',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p2',
    'stage_id': 's7',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p2',
    'stage_id': 's8',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p2',
    'stage_id': 's9',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p2',
    'stage_id': 's10',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p2',
    'stage_id': 's11',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p2',
    'stage_id': 's12',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p3',
    'stage_id': 's13',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p3',
    'stage_id': 's14',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p3',
    'stage_id': 's15',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p3',
    'stage_id': 's16',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p3',
    'stage_id': 's17',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p3',
    'stage_id': 's18',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p4',
    'stage_id': 's19',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p4',
    'stage_id': 's20',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p4',
    'stage_id': 's21',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p4',
    'stage_id': 's22',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p4',
    'stage_id': 's23',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p4',
    'stage_id': 's24',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p5',
    'stage_id': 's25',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p5',
    'stage_id': 's26',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p5',
    'stage_id': 's27',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p5',
    'stage_id': 's28',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p5',
    'stage_id': 's29',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p5',
    'stage_id': 's30',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p6',
    'stage_id': 's31',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p6',
    'stage_id': 's32',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p6',
    'stage_id': 's33',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p6',
    'stage_id': 's34',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p6',
    'stage_id': 's35',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p6',
    'stage_id': 's36',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p7',
    'stage_id': 's37',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p7',
    'stage_id': 's38',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p7',
    'stage_id': 's39',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p7',
    'stage_id': 's40',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p7',
    'stage_id': 's41',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p7',
    'stage_id': 's42',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p8',
    'stage_id': 's43',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p8',
    'stage_id': 's44',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p8',
    'stage_id': 's45',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p8',
    'stage_id': 's46',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p8',
    'stage_id': 's47',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p8',
    'stage_id': 's48',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p9',
    'stage_id': 's49',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p9',
    'stage_id': 's50',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p9',
    'stage_id': 's51',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p9',
    'stage_id': 's52',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p9',
    'stage_id': 's53',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p9',
    'stage_id': 's54',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p10',
    'stage_id': 's55',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p10',
    'stage_id': 's56',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p10',
    'stage_id': 's57',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p10',
    'stage_id': 's58',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p10',
    'stage_id': 's59',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p10',
    'stage_id': 's60',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p11',
    'stage_id': 's61',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p11',
    'stage_id': 's62',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p11',
    'stage_id': 's63',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p11',
    'stage_id': 's64',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p11',
    'stage_id': 's65',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p11',
    'stage_id': 's66',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p12',
    'stage_id': 's67',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p12',
    'stage_id': 's68',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p12',
    'stage_id': 's69',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p12',
    'stage_id': 's70',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p12',
    'stage_id': 's71',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p12',
    'stage_id': 's72',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p13',
    'stage_id': 's73',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p13',
    'stage_id': 's74',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p13',
    'stage_id': 's75',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p13',
    'stage_id': 's76',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p13',
    'stage_id': 's77',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p13',
    'stage_id': 's78',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p14',
    'stage_id': 's79',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p14',
    'stage_id': 's80',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p14',
    'stage_id': 's81',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p14',
    'stage_id': 's82',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p14',
    'stage_id': 's83',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p14',
    'stage_id': 's84',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p15',
    'stage_id': 's85',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p15',
    'stage_id': 's86',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p15',
    'stage_id': 's87',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p15',
    'stage_id': 's88',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p15',
    'stage_id': 's89',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p15',
    'stage_id': 's90',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p16',
    'stage_id': 's91',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p16',
    'stage_id': 's92',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p16',
    'stage_id': 's93',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p16',
    'stage_id': 's94',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p16',
    'stage_id': 's95',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p16',
    'stage_id': 's96',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p17',
    'stage_id': 's97',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p17',
    'stage_id': 's98',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p17',
    'stage_id': 's99',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p17',
    'stage_id': 's100',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p17',
    'stage_id': 's101',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p17',
    'stage_id': 's102',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p18',
    'stage_id': 's103',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p18',
    'stage_id': 's104',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p18',
    'stage_id': 's105',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p18',
    'stage_id': 's106',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p18',
    'stage_id': 's107',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p18',
    'stage_id': 's108',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p19',
    'stage_id': 's109',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p19',
    'stage_id': 's110',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p19',
    'stage_id': 's111',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p19',
    'stage_id': 's112',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p19',
    'stage_id': 's113',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p19',
    'stage_id': 's114',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p20',
    'stage_id': 's115',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p20',
    'stage_id': 's116',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p20',
    'stage_id': 's117',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p20',
    'stage_id': 's118',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p20',
    'stage_id': 's119',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p20',
    'stage_id': 's120',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p21',
    'stage_id': 's121',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p21',
    'stage_id': 's122',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p21',
    'stage_id': 's123',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p21',
    'stage_id': 's124',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p21',
    'stage_id': 's125',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p21',
    'stage_id': 's126',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p22',
    'stage_id': 's127',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p22',
    'stage_id': 's128',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p22',
    'stage_id': 's129',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p22',
    'stage_id': 's130',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p22',
    'stage_id': 's131',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p22',
    'stage_id': 's132',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p23',
    'stage_id': 's133',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p23',
    'stage_id': 's134',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p23',
    'stage_id': 's135',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p23',
    'stage_id': 's136',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p23',
    'stage_id': 's137',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p23',
    'stage_id': 's138',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p24',
    'stage_id': 's139',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p24',
    'stage_id': 's140',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p24',
    'stage_id': 's141',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p24',
    'stage_id': 's142',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p24',
    'stage_id': 's143',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p24',
    'stage_id': 's144',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p25',
    'stage_id': 's145',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p25',
    'stage_id': 's146',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p25',
    'stage_id': 's147',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p25',
    'stage_id': 's148',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p25',
    'stage_id': 's149',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p25',
    'stage_id': 's150',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p26',
    'stage_id': 's151',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p26',
    'stage_id': 's152',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p26',
    'stage_id': 's153',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p26',
    'stage_id': 's154',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p26',
    'stage_id': 's155',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p26',
    'stage_id': 's156',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p27',
    'stage_id': 's157',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p27',
    'stage_id': 's158',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p27',
    'stage_id': 's159',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p27',
    'stage_id': 's160',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p27',
    'stage_id': 's161',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p27',
    'stage_id': 's162',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p28',
    'stage_id': 's163',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p28',
    'stage_id': 's164',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p28',
    'stage_id': 's165',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p28',
    'stage_id': 's166',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p28',
    'stage_id': 's167',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p28',
    'stage_id': 's168',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p29',
    'stage_id': 's169',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p29',
    'stage_id': 's170',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p29',
    'stage_id': 's171',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p29',
    'stage_id': 's172',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p29',
    'stage_id': 's173',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p29',
    'stage_id': 's174',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p30',
    'stage_id': 's175',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p30',
    'stage_id': 's176',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p30',
    'stage_id': 's177',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p30',
    'stage_id': 's178',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p30',
    'stage_id': 's179',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p30',
    'stage_id': 's180',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p31',
    'stage_id': 's181',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p31',
    'stage_id': 's182',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p31',
    'stage_id': 's183',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p31',
    'stage_id': 's184',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p31',
    'stage_id': 's185',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p31',
    'stage_id': 's186',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p32',
    'stage_id': 's187',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p32',
    'stage_id': 's188',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p32',
    'stage_id': 's189',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p32',
    'stage_id': 's190',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p32',
    'stage_id': 's191',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p32',
    'stage_id': 's192',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p33',
    'stage_id': 's193',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p33',
    'stage_id': 's194',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p33',
    'stage_id': 's195',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p33',
    'stage_id': 's196',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p33',
    'stage_id': 's197',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p33',
    'stage_id': 's198',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p34',
    'stage_id': 's199',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p34',
    'stage_id': 's200',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p34',
    'stage_id': 's201',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p34',
    'stage_id': 's202',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p34',
    'stage_id': 's203',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p34',
    'stage_id': 's204',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p35',
    'stage_id': 's205',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p35',
    'stage_id': 's206',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p35',
    'stage_id': 's207',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p35',
    'stage_id': 's208',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p35',
    'stage_id': 's209',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p35',
    'stage_id': 's210',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p36',
    'stage_id': 's211',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p36',
    'stage_id': 's212',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p36',
    'stage_id': 's213',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p36',
    'stage_id': 's214',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p36',
    'stage_id': 's215',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p36',
    'stage_id': 's216',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p37',
    'stage_id': 's217',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p37',
    'stage_id': 's218',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p37',
    'stage_id': 's219',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p37',
    'stage_id': 's220',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p37',
    'stage_id': 's221',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p37',
    'stage_id': 's222',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p38',
    'stage_id': 's223',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p38',
    'stage_id': 's224',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p38',
    'stage_id': 's225',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p38',
    'stage_id': 's226',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p38',
    'stage_id': 's227',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p38',
    'stage_id': 's228',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p39',
    'stage_id': 's229',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p39',
    'stage_id': 's230',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p39',
    'stage_id': 's231',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p39',
    'stage_id': 's232',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p39',
    'stage_id': 's233',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p39',
    'stage_id': 's234',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p40',
    'stage_id': 's235',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p40',
    'stage_id': 's236',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p40',
    'stage_id': 's237',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p40',
    'stage_id': 's238',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p40',
    'stage_id': 's239',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p40',
    'stage_id': 's240',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p41',
    'stage_id': 's241',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p41',
    'stage_id': 's242',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p41',
    'stage_id': 's243',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p41',
    'stage_id': 's244',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p41',
    'stage_id': 's245',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p41',
    'stage_id': 's246',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p42',
    'stage_id': 's247',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p42',
    'stage_id': 's248',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p42',
    'stage_id': 's249',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p42',
    'stage_id': 's250',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p42',
    'stage_id': 's251',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p42',
    'stage_id': 's252',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p43',
    'stage_id': 's253',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p43',
    'stage_id': 's254',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p43',
    'stage_id': 's255',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p43',
    'stage_id': 's256',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p43',
    'stage_id': 's257',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p43',
    'stage_id': 's258',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p44',
    'stage_id': 's259',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p44',
    'stage_id': 's260',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p44',
    'stage_id': 's261',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p44',
    'stage_id': 's262',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p44',
    'stage_id': 's263',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p44',
    'stage_id': 's264',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p45',
    'stage_id': 's265',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p45',
    'stage_id': 's266',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p45',
    'stage_id': 's267',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p45',
    'stage_id': 's268',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p45',
    'stage_id': 's269',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p45',
    'stage_id': 's270',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p46',
    'stage_id': 's271',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p46',
    'stage_id': 's272',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p46',
    'stage_id': 's273',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p46',
    'stage_id': 's274',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p46',
    'stage_id': 's275',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p46',
    'stage_id': 's276',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p47',
    'stage_id': 's277',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p47',
    'stage_id': 's278',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p47',
    'stage_id': 's279',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p47',
    'stage_id': 's280',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p47',
    'stage_id': 's281',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p47',
    'stage_id': 's282',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p48',
    'stage_id': 's283',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p48',
    'stage_id': 's284',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p48',
    'stage_id': 's285',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p48',
    'stage_id': 's286',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p48',
    'stage_id': 's287',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p48',
    'stage_id': 's288',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p49',
    'stage_id': 's289',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p49',
    'stage_id': 's290',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p49',
    'stage_id': 's291',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p49',
    'stage_id': 's292',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p49',
    'stage_id': 's293',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p49',
    'stage_id': 's294',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p50',
    'stage_id': 's295',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p50',
    'stage_id': 's296',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p50',
    'stage_id': 's297',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p50',
    'stage_id': 's298',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p50',
    'stage_id': 's299',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p50',
    'stage_id': 's300',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p51',
    'stage_id': 's301',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p51',
    'stage_id': 's302',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p51',
    'stage_id': 's303',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p51',
    'stage_id': 's304',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p51',
    'stage_id': 's305',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p51',
    'stage_id': 's306',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p52',
    'stage_id': 's307',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p52',
    'stage_id': 's308',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p52',
    'stage_id': 's309',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p52',
    'stage_id': 's310',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p52',
    'stage_id': 's311',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p52',
    'stage_id': 's312',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p53',
    'stage_id': 's313',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p53',
    'stage_id': 's314',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p53',
    'stage_id': 's315',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p53',
    'stage_id': 's316',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p53',
    'stage_id': 's317',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p53',
    'stage_id': 's318',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p54',
    'stage_id': 's319',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p54',
    'stage_id': 's320',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p54',
    'stage_id': 's321',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p54',
    'stage_id': 's322',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p54',
    'stage_id': 's323',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p54',
    'stage_id': 's324',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p55',
    'stage_id': 's325',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p55',
    'stage_id': 's326',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p55',
    'stage_id': 's327',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p55',
    'stage_id': 's328',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p55',
    'stage_id': 's329',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p55',
    'stage_id': 's330',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p56',
    'stage_id': 's331',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p56',
    'stage_id': 's332',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p56',
    'stage_id': 's333',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p56',
    'stage_id': 's334',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p56',
    'stage_id': 's335',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p56',
    'stage_id': 's336',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p57',
    'stage_id': 's337',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p57',
    'stage_id': 's338',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p57',
    'stage_id': 's339',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p57',
    'stage_id': 's340',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p57',
    'stage_id': 's341',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p57',
    'stage_id': 's342',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p58',
    'stage_id': 's343',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p58',
    'stage_id': 's344',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p58',
    'stage_id': 's345',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p58',
    'stage_id': 's346',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p58',
    'stage_id': 's347',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p58',
    'stage_id': 's348',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p59',
    'stage_id': 's349',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p59',
    'stage_id': 's350',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p59',
    'stage_id': 's351',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p59',
    'stage_id': 's352',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p59',
    'stage_id': 's353',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p59',
    'stage_id': 's354',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p60',
    'stage_id': 's355',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p60',
    'stage_id': 's356',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p60',
    'stage_id': 's357',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p60',
    'stage_id': 's358',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p60',
    'stage_id': 's359',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p60',
    'stage_id': 's360',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p61',
    'stage_id': 's361',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p61',
    'stage_id': 's362',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p61',
    'stage_id': 's363',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p61',
    'stage_id': 's364',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p61',
    'stage_id': 's365',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p61',
    'stage_id': 's366',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p62',
    'stage_id': 's367',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p62',
    'stage_id': 's368',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p62',
    'stage_id': 's369',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p62',
    'stage_id': 's370',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p62',
    'stage_id': 's371',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p62',
    'stage_id': 's372',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p63',
    'stage_id': 's373',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p63',
    'stage_id': 's374',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p63',
    'stage_id': 's375',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p63',
    'stage_id': 's376',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p63',
    'stage_id': 's377',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p63',
    'stage_id': 's378',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p64',
    'stage_id': 's379',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p64',
    'stage_id': 's380',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p64',
    'stage_id': 's381',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p64',
    'stage_id': 's382',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p64',
    'stage_id': 's383',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p64',
    'stage_id': 's384',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p65',
    'stage_id': 's385',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p65',
    'stage_id': 's386',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p65',
    'stage_id': 's387',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p65',
    'stage_id': 's388',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p65',
    'stage_id': 's389',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p65',
    'stage_id': 's390',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p66',
    'stage_id': 's391',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p66',
    'stage_id': 's392',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p66',
    'stage_id': 's393',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p66',
    'stage_id': 's394',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p66',
    'stage_id': 's395',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p66',
    'stage_id': 's396',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p67',
    'stage_id': 's397',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p67',
    'stage_id': 's398',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p67',
    'stage_id': 's399',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p67',
    'stage_id': 's400',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p67',
    'stage_id': 's401',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p67',
    'stage_id': 's402',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p68',
    'stage_id': 's403',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p68',
    'stage_id': 's404',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p68',
    'stage_id': 's405',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p68',
    'stage_id': 's406',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p68',
    'stage_id': 's407',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p68',
    'stage_id': 's408',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p69',
    'stage_id': 's409',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p69',
    'stage_id': 's410',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p69',
    'stage_id': 's411',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p69',
    'stage_id': 's412',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p69',
    'stage_id': 's413',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p69',
    'stage_id': 's414',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p70',
    'stage_id': 's415',
    'water_mm_per_day': 2.0},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p70',
    'stage_id': 's416',
    'water_mm_per_day': 3.2},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 2,
    'plant_id': 'p70',
    'stage_id': 's417',
    'water_mm_per_day': 4.4},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p70',
    'stage_id': 's418',
    'water_mm_per_day': 5.6},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 1,
    'plant_id': 'p70',
    'stage_id': 's419',
    'water_mm_per_day': 2.8},
  { 'drought_tolerance': 'Medium',
    'irrigation_frequency_days': 3,
    'plant_id': 'p70',
    'stage_id': 's420',
    'water_mm_per_day': 2.0}]
