"""Move bio data to varieties

Revision ID: 74392601755b
Revises: 421899d0499d
Create Date: 2026-07-18 02:00:28.624165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74392601755b'
down_revision: Union[str, Sequence[str], None] = '421899d0499d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_varieties', sa.Column('scientific_name', sa.String(length=100), nullable=True))
    op.add_column('plant_varieties', sa.Column('planting_season', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('plant_varieties', sa.Column('optimal_temp_min', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('plant_varieties', sa.Column('optimal_temp_max', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('plant_varieties', sa.Column('optimal_rainfall_mm', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('plant_varieties', sa.Column('optimal_ph_min', sa.Numeric(precision=3, scale=1), nullable=True))
    op.add_column('plant_varieties', sa.Column('optimal_ph_max', sa.Numeric(precision=3, scale=1), nullable=True))
    op.add_column('plant_varieties', sa.Column('expected_yield_per_acre_kg', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('plant_varieties', sa.Column('compatible_soil_types', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('plant_varieties', sa.Column('companion_plants', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('plant_varieties', sa.Column('incompatible_plants', postgresql.ARRAY(sa.String()), nullable=True))
    op.alter_column('plant_varieties', 'growth_duration_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('plants', 'optimal_ph_max')
    op.drop_column('plants', 'planting_season')
    op.drop_column('plants', 'companion_plants')
    op.drop_column('plants', 'optimal_rainfall_mm')
    op.drop_column('plants', 'expected_yield_per_acre_kg')
    op.drop_column('plants', 'scientific_name')
    op.drop_column('plants', 'optimal_temp_min')
    op.drop_column('plants', 'incompatible_plants')
    op.drop_column('plants', 'compatible_soil_types')
    op.drop_column('plants', 'optimal_temp_max')
    op.drop_column('plants', 'growth_duration_days')
    op.drop_column('plants', 'optimal_ph_min')
    op.alter_column('projects', 'variety_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('fk_projects_variety_id_plant_varieties'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'plant_varieties', ['variety_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_projects_variety_id_plant_varieties'), 'projects', 'plant_varieties', ['variety_id'], ['id'], ondelete='SET NULL')
    op.alter_column('projects', 'variety_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('plants', sa.Column('optimal_ph_min', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('growth_duration_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('plants', sa.Column('optimal_temp_max', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('compatible_soil_types', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('incompatible_plants', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('optimal_temp_min', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('scientific_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('expected_yield_per_acre_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('optimal_rainfall_mm', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('companion_plants', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('planting_season', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('optimal_ph_max', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True))
    op.alter_column('plant_varieties', 'growth_duration_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('plant_varieties', 'incompatible_plants')
    op.drop_column('plant_varieties', 'companion_plants')
    op.drop_column('plant_varieties', 'compatible_soil_types')
    op.drop_column('plant_varieties', 'expected_yield_per_acre_kg')
    op.drop_column('plant_varieties', 'optimal_ph_max')
    op.drop_column('plant_varieties', 'optimal_ph_min')
    op.drop_column('plant_varieties', 'optimal_rainfall_mm')
    op.drop_column('plant_varieties', 'optimal_temp_max')
    op.drop_column('plant_varieties', 'optimal_temp_min')
    op.drop_column('plant_varieties', 'planting_season')
    op.drop_column('plant_varieties', 'scientific_name')
    # ### end Alembic commands ###
