"""Add product categories

Revision ID: f84bd166f390
Revises: 74392601755b
Create Date: 2026-07-18 05:59:53.616495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84bd166f390'
down_revision: Union[str, Sequence[str], None] = '74392601755b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_subcategories',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_subcategories_category_id'), 'product_subcategories', ['category_id'], unique=False)
    op.add_column('products', sa.Column('category_id', sa.UUID(), nullable=False))
    op.add_column('products', sa.Column('sub_category_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_sub_category_id'), 'products', ['sub_category_id'], unique=False)
    op.create_foreign_key(None, 'products', 'product_subcategories', ['sub_category_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'products', 'product_categories', ['category_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_sub_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_column('products', 'sub_category_id')
    op.drop_column('products', 'category_id')
    op.drop_index(op.f('ix_product_subcategories_category_id'), table_name='product_subcategories')
    op.drop_table('product_subcategories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
